import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, readdir, rm } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { APPLICABILITY_STATUSES, ESTIMATOR_SELECTION_POLICY_V01, evaluateEstimatorApplicability } from '../src/token-intelligence/estimator-applicability.mjs';
import { compareConditionalReplay, createConditionalForecast } from '../src/token-intelligence/conditional-estimator.mjs';
import { main } from '../scripts/starbench-workbench.mjs';

const root = resolve(import.meta.dirname, '..');
const read = async path => JSON.parse(await readFile(join(root, ...path.split('/')), 'utf8'));
async function productionArtifacts(goal) {
  const base = join(root, 'reports', goal, 'pre-execution', 'production');
  const directory = (await readdir(base, { withFileTypes: true })).find(x => x.isDirectory() && x.name.startsWith('forecast_run_')).name;
  return { graphs: await readFile(join(base, directory, 'graphs.json'), 'utf8').then(JSON.parse), forecast: await readFile(join(base, directory, 'forecast.json'), 'utf8').then(JSON.parse), seal: await readFile(join(base, directory, 'forecast-seal.json'), 'utf8').then(JSON.parse) };
}
const cases = async () => ({
  B: { graphs: await read('reports/goal-e/shadow/goal-b/shadow-source-graphs.json'), forecast: await read('reports/goal-e/shadow/goal-b/shadow-source-forecast.json'), shadow: await read('reports/goal-e/shadow/goal-b/session-aware-shadow.json'), comparison: await read('reports/goal-e/comparisons/goal-b.json') },
  O: { graphs: await read('reports/goal-e/shadow/overnight-002/shadow-source-graphs.json'), forecast: await read('reports/goal-e/shadow/overnight-002/shadow-source-forecast.json'), shadow: await read('reports/goal-e/shadow/overnight-002/session-aware-shadow.json'), comparison: await read('reports/goal-e/comparisons/overnight-002.json') },
  D: { graphs: await read('reports/goal-e/shadow/goal-d/shadow-source-graphs.json'), comparison: await read('reports/goal-e/comparisons/goal-d.json') }
});

test('Goal H own Production and Shadow V1 Forecasts were independently sealed before implementation', async () => {
  const a = await productionArtifacts('goal-h'), shadow = await read('reports/goal-h/pre-execution/shadow/shadow-forecast-seal.json'), experimentName = (await readdir(join(root, 'reports/goal-h/registry')))[0], experiment = await readFile(join(root, 'reports/goal-h/registry', experimentName), 'utf8').then(JSON.parse);
  assert.equal(a.seal.status, 'SEALED'); assert.equal(shadow.status, 'SEALED'); assert.notEqual(a.seal.forecast_id, shadow.shadow_forecast_id);
  assert.equal(experiment.experiment_status, 'SEALED_AWAITING_EXECUTION'); assert.equal(experiment.comparison_status, 'AWAITING_ACTUAL'); assert.equal(experiment.actual_receipt_id, null);
});
test('Policy is experimental and has conservative fallbacks with no forbidden runtime inputs', () => {
  const p = ESTIMATOR_SELECTION_POLICY_V01; assert.equal(p.status, 'EXPERIMENTAL'); assert.equal(p.default_estimator, 'PRODUCTION'); assert.equal(p.fallback.AMBIGUOUS, 'PRODUCTION'); assert.equal(p.fallback.INSUFFICIENT_EVIDENCE, 'PRODUCTION');
  assert.equal(p.truthfulness.actual_available_to_gate, false); assert.equal(p.truthfulness.goal_identity_available_to_gate, false); assert.equal(p.truthfulness.token_total_routing, false); assert.equal(p.truthfulness.fixed_multiplier, false);
});
test('all required applicability statuses are represented by the contract', () => assert.deepEqual(APPLICABILITY_STATUSES, ['SHADOW_APPLICABLE','PRODUCTION_PREFERRED','INSUFFICIENT_EVIDENCE','AMBIGUOUS','INVALID_INPUT']));
test('Goal B counterexample selects Production from pre-execution fragmentation', async () => { const x = (await cases()).B, r = evaluateEstimatorApplicability({ graph: x.graphs.expected }); assert.equal(r.decision.status, 'PRODUCTION_PREFERRED'); assert.equal(r.decision.selected_estimator, 'PRODUCTION'); assert.equal(r.audit.features.execution_session_count, 7); });
test('Overnight 002 conservatively selects Production and retains retrospective class later', async () => { const x = (await cases()).O, r = evaluateEstimatorApplicability({ graph: x.graphs.expected }); assert.equal(r.decision.status, 'PRODUCTION_PREFERRED'); assert.equal(r.decision.selected_estimator, 'PRODUCTION'); const replay = compareConditionalReplay({ decision: r.decision, production_forecast: x.comparison.old_forecast, shadow_forecast: x.comparison.shadow_forecast, actual_total_tokens: x.comparison.actual_tokens, evidence_class: x.comparison.evidence_class, evidence_source_ref: 'Overnight 002' }); assert.equal(replay.evidence_class, 'RETROSPECTIVE_MODEL_EVALUATION'); assert.equal(replay.replay_outcome, 'CONSERVATIVE_PRODUCTION_TRADEOFF'); });
test('Goal D prospective structure selects Shadow V1 without Actual input', async () => { const x = (await cases()).D, r = evaluateEstimatorApplicability({ graph: x.graphs.expected }); assert.equal(r.decision.status, 'SHADOW_APPLICABLE'); assert.equal(r.decision.selected_estimator, 'SHADOW_V1'); assert.equal(r.audit.input_boundary.actual_received, false); });
test('Goal F and Goal G prospective long Goals select Shadow V1 from semantic continuity', async () => { for (const goal of ['goal-f','goal-g']) { const a = await productionArtifacts(goal), r = evaluateEstimatorApplicability({ graph: a.graphs.expected }); assert.equal(r.decision.status, 'SHADOW_APPLICABLE'); assert.equal(r.decision.selected_estimator, 'SHADOW_V1'); assert.equal(r.audit.features.execution_session_count, 1); } });
test('Conditional Forecast preserves the selected Production path exactly for Goal B', async () => { const x = (await cases()).B, r = createConditionalForecast({ graph: x.graphs.expected, productionForecast: x.forecast, shadowForecast: x.shadow }); assert.equal(r.status, 'READY'); assert.equal(r.conditional_forecast.selected_estimator, 'PRODUCTION'); assert.deepEqual(r.conditional_forecast.selected_forecast, { optimistic: x.forecast.optimistic_path.total_tokens, expected: x.forecast.expected_path.total_tokens, conservative: x.forecast.conservative_path.total_tokens }); assert.equal(r.conditional_forecast.truthfulness.selected_path_recalculated, false); });
test('insufficient evidence and ambiguous outcomes fall back to Production', async () => { const x = structuredClone((await cases()).B.graphs.expected); x.work_units = x.work_units.slice(0, 5); const ids = new Set(x.work_units.map(u => u.work_unit_id)); for (const u of x.work_units) u.dependencies = u.dependencies.filter(id => ids.has(id)); x.graph_id = `graph_${'a'.repeat(64)}`; const r = evaluateEstimatorApplicability({ graph: x }); assert.equal(r.decision.status, 'INSUFFICIENT_EVIDENCE'); assert.equal(r.decision.selected_estimator, 'PRODUCTION'); assert.equal(r.decision.fallback_applied, true); });
test('invalid Work Graph is rejected without choosing an estimator', () => { const r = evaluateEstimatorApplicability({ graph: {} }); assert.equal(r.decision.status, 'INVALID_INPUT'); assert.equal(r.decision.selected_estimator, null); });
test('replay accepts Actual only after a frozen decision and does not recompute it', async () => { const x = (await cases()).B, d = evaluateEstimatorApplicability({ graph: x.graphs.expected }).decision, replay = compareConditionalReplay({ decision: d, production_forecast: x.comparison.old_forecast, shadow_forecast: x.comparison.shadow_forecast, actual_total_tokens: x.comparison.actual_tokens, evidence_class: x.comparison.evidence_class, evidence_source_ref: 'Goal B' }); assert.equal(replay.decision_id, d.decision_id); assert.equal(replay.decision_frozen_before_actual, true); assert.equal(replay.truthfulness.decision_recomputed_after_actual, false); assert.equal(replay.replay_outcome, 'SELECTION_SUPPORTED'); });
test('Goal H schemas are Draft 2020-12 contracts', async () => { for (const name of ['estimator-applicability-decision-v0.1.schema.json','estimator-selection-policy-v0.1.schema.json','conditional-forecast-v0.1.schema.json','conditional-replay-v0.1.schema.json']) assert.equal((await read(`schemas/${name}`)).$schema, 'https://json-schema.org/draft/2020-12/schema'); });
test('Gate source has no network, credential, randomness, fixed multiplier, or outcome-based branch', async () => { const source = await readFile(join(root, 'src/token-intelligence/estimator-applicability.mjs'), 'utf8'); assert.doesNotMatch(source, /fetch\s*\(|process\.env|Authorization|provider-adapter|Math\.random|0\.59|0\.6|actual_total_tokens\s*[<>=]|forecast_error\s*[<>=]|closeout_winner\s*[<>=]/iu); assert.match(source, /evaluateEstimatorApplicability\(\{ graph \}\)/u); });
test('Goal H CLI exposes separate selection and post-decision comparison commands', async () => { const x = (await cases()).B, dir = await mkdtemp(join(tmpdir(), 'sb-goal-h-')); try { await import('node:fs/promises').then(fs => Promise.all([fs.writeFile(join(dir,'graphs.json'), JSON.stringify(x.graphs)), fs.writeFile(join(dir,'forecast.json'), JSON.stringify(x.forecast)), fs.writeFile(join(dir,'shadow.json'), JSON.stringify(x.shadow))])); assert.equal(await main(['estimator-applicability','--graphs','graphs.json','--output','decision.json'], { rootDir: dir }), 0); assert.equal((await readFile(join(dir,'decision.json'),'utf8').then(JSON.parse)).decision.selected_estimator, 'PRODUCTION'); assert.equal(await main(['conditional-forecast','--graphs','graphs.json','--forecast','forecast.json','--shadow','shadow.json','--output','conditional.json'], { rootDir: dir }), 0); } finally { await rm(dir, { recursive: true, force: true }); } });
