import assert from 'node:assert/strict';
import { readFile, rm } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import test, { after } from 'node:test';
import { fileURLToPath } from 'node:url';

import { ProjectTokenIntelligenceEngine } from '../src/token-intelligence/forecast-engine.mjs';
import { buildWorkGraphs } from '../src/token-intelligence/work-graph-builder.mjs';
import { calibrateGraphs } from '../src/token-intelligence/historical-calibrator.mjs';
import { HistoricalUsageStore } from '../src/token-intelligence/historical-usage-store.mjs';
import { classifyHistoricalUsageRecord } from '../src/token-intelligence/historical-usage-validator.mjs';
import { intakeHistoricalUsageBatch, intakeHistoricalUsageFile, intakeHistoricalUsageJsonl, persistHistoricalUsageReceipt } from '../src/token-intelligence/historical-usage-intake.mjs';
import { HistoricalIntakeReceiptStore } from '../src/token-intelligence/historical-intake-receipt-store.mjs';
import { bindResourceSnapshots, validateEntitlementSnapshotRef, validatePricingSnapshotRef } from '../src/token-intelligence/resource-snapshot-consumer.mjs';
import { appendAuditReferenceToSummary, buildForecastExplanationAudit } from '../src/token-intelligence/forecast-explanation-audit.mjs';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const fixtureDir = join(root, 'tests', 'fixtures', 'token-intelligence');
const tempRoot = join(root, 'tests', '.tmp-night-goal-001');
const provenance = { source_type:'TEST_FIXTURE', source_ref:'tests/fixtures/token-intelligence/historical-usage-night-dry-run.jsonl', imported_at:'2026-08-13T00:00:00.000Z', evidence_quality:'TEST_FIXTURE', field_provenance:{ canonical_record:'fixture JSONL' }, token_provenance:'fixture observations or explicit null', duration_provenance:'fixture observations', execution_provenance:'fixture only; no provider execution' };
let networkRequests=0; const originalFetch=globalThis.fetch; globalThis.fetch=async()=>{networkRequests+=1;throw new Error('NETWORK_FORBIDDEN');};
after(async()=>{globalThis.fetch=originalFetch;await rm(tempRoot,{recursive:true,force:true});});
const json=async(name)=>JSON.parse(await readFile(join(fixtureDir,name),'utf8'));
const dryRunContent=await readFile(join(fixtureDir,'historical-usage-night-dry-run.jsonl'),'utf8');
const dryRunLines=dryRunContent.trim().split(/\r?\n/u).map(JSON.parse);
const receipt=intakeHistoricalUsageJsonl(dryRunContent,{provenance});
const complex=await json('project-complex.json'); const risk=await json('project-risk.json');
const pricingCurrent=await json('pricing-snapshot-current.fixture.json'); const pricingStale=await json('pricing-snapshot-stale.fixture.json'); const pricingUnknown=await json('pricing-snapshot-unknown.fixture.json');
const entitlementCurrent=await json('entitlement-snapshot-current.fixture.json'); const entitlementUnknown=await json('entitlement-snapshot-unknown.fixture.json');
const engine=new ProjectTokenIntelligenceEngine();

const expectedSchemas={
  'historical-usage-intake-receipt-v0.1.schema.json':'HISTORICAL_USAGE_INTAKE_RECEIPT',
  'pricing-snapshot-ref-v0.1.schema.json':'PRICING_SNAPSHOT_REF',
  'entitlement-snapshot-ref-v0.1.schema.json':'ENTITLEMENT_SNAPSHOT_REF',
  'resource-snapshot-binding-v0.1.schema.json':'RESOURCE_SNAPSHOT_BINDING',
  'forecast-explanation-audit-v0.1.schema.json':'FORECAST_EXPLANATION_AUDIT',
};
test('five additive Night Goal schemas parse with exact record types',async()=>{for(const [name,type] of Object.entries(expectedSchemas)){const schema=JSON.parse(await readFile(join(root,'schemas',name),'utf8'));assert.equal(schema.properties.record_type.const,type);assert.equal(schema.additionalProperties,false);}});
test('no formal 00 Historical Export is present inside StarBench',async()=>{const candidates=['historical-export.jsonl','00-historical-export.jsonl','historical-usage-export.jsonl'];for(const name of candidates)await assert.rejects(readFile(join(root,name),'utf8'),{code:'ENOENT'});});
test('validator classifies complete observed usage as KNOWN',()=>{const result=classifyHistoricalUsageRecord(dryRunLines[0]);assert.equal(result.classification,'KNOWN');assert.equal(result.valid,true);assert.equal(result.field_states.total_tokens,'KNOWN');});
test('validator classifies null token telemetry as UNKNOWN without converting it to zero',()=>{const record=dryRunLines[2];const result=classifyHistoricalUsageRecord(record);assert.equal(result.classification,'UNKNOWN');for(const key of ['input_tokens','cached_input_tokens','output_tokens','reasoning_tokens','total_tokens']){assert.equal(record[key],null);assert.equal(result.field_states[key],'UNKNOWN');}assert.equal(record.calls,2);});
test('validator rejects invalid records as INVALID',()=>{const result=classifyHistoricalUsageRecord(dryRunLines[6]);assert.equal(result.classification,'INVALID');assert.equal(result.valid,false);});
test('validator detects same identity with conflicting canonical content',()=>{const result=classifyHistoricalUsageRecord(dryRunLines[5],{existingRecords:[dryRunLines[0]]});assert.equal(result.classification,'CONFLICT');assert.equal(result.valid,false);assert.deepEqual(result.error_codes,['USAGE_RECORD_ID_CONFLICT']);});
test('provider, model, duration, and provenance types are validated before intake',()=>{for(const mutation of [r=>{r.provider=42;},r=>{r.model={};},r=>{r.duration='120';},r=>{r.provenance.source_class='UNAUTHORIZED';}]){const record=structuredClone(dryRunLines[0]);mutation(record);const result=classifyHistoricalUsageRecord(record);assert.equal(result.classification,'INVALID');assert.equal(result.valid,false);}});test('provenance contradictions are INVALID',()=>{const record=structuredClone(dryRunLines[2]);record.provenance.unknown_fields=[];record.provenance.observed_fields.push('total_tokens');const result=classifyHistoricalUsageRecord(record);assert.equal(result.classification,'INVALID');assert.ok(result.error_codes.includes('OBSERVED_FIELD_IS_NULL:total_tokens'));});
test('batch intake accepts valid partial records and summarizes duplicates/rejections',()=>{assert.equal(receipt.status,'PARTIAL');assert.deepEqual(receipt.summary,{total:7,accepted:4,known:3,unknown:1,duplicates:1,invalid:1,conflicts:1,rejected:2});assert.deepEqual(receipt.truthfulness,{missing_tokens_inferred:false,unknown_preserved:true,legacy_summary_promoted:false});});
test('intake receipt retains import provenance separately from canonical records',()=>{assert.equal(receipt.provenance.source_type,'TEST_FIXTURE');assert.equal(receipt.provenance.source_ref,provenance.source_ref);assert.ok(receipt.accepted_records.every((record)=>record.provenance.source_class==='TEST_FIXTURE'));assert.ok(receipt.accepted_records.every((record)=>!('imported_at' in record.provenance)));});
test('JSONL parse errors are summarized without discarding valid entries',()=>{const value=intakeHistoricalUsageJsonl(`${JSON.stringify(dryRunLines[0])}\n{bad json}`,{provenance});assert.equal(value.summary.accepted,1);assert.equal(value.summary.invalid,1);assert.equal(value.status,'PARTIAL');});
test('invalid intake provenance fails closed',()=>{assert.throws(()=>intakeHistoricalUsageBatch([dryRunLines[0]],{provenance:{...provenance,source_type:'UNAUTHORIZED'}}),{code:'HISTORICAL_INTAKE_PROVENANCE_INVALID'});});
test('accepted intake records persist through canonical Historical Usage Store',async()=>{await rm(tempRoot,{recursive:true,force:true});const store=new HistoricalUsageStore({rootDir:root,filePath:join(tempRoot,'history.jsonl')});const result=await persistHistoricalUsageReceipt(receipt,store);assert.equal(result.written,4);assert.equal((await store.readAll()).length,4);assert.equal((await store.queryByBillingMode('SUBSCRIPTION_QUOTA')).length,2);});
test('re-persisting an intake receipt is idempotent',async()=>{const store=new HistoricalUsageStore({rootDir:root,filePath:join(tempRoot,'history.jsonl')});const result=await persistHistoricalUsageReceipt(receipt,store);assert.equal(result.written,0);assert.equal(result.duplicate_skipped,4);});
test('StarBench-local Export file intake is root-bounded',async()=>{const value=await intakeHistoricalUsageFile(join(fixtureDir,'historical-usage-night-dry-run.jsonl'),{rootDir:root,provenance});assert.deepEqual(value.summary,receipt.summary);await assert.rejects(intakeHistoricalUsageFile(resolve(root,'..','outside-history.jsonl'),{rootDir:root,provenance}),{code:'HISTORICAL_EXPORT_PATH_ESCAPE'});});
test('Receipt Store persists batch provenance and traces a usage ID',async()=>{const store=new HistoricalIntakeReceiptStore({rootDir:root,filePath:join(tempRoot,'receipts.jsonl')});assert.equal((await store.write(receipt)).status,'written');assert.equal((await store.write(receipt)).status,'duplicate_skipped');const trace=await store.traceUsageRecord(dryRunLines[0].usage_record_id);assert.equal(trace.length,1);assert.equal(trace[0].source_type,'TEST_FIXTURE');assert.equal(trace[0].source_ref,provenance.source_ref);assert.equal(trace[0].outcome.disposition,'ACCEPTED');});
test('Receipt Store rejects path escape',()=>{assert.throws(()=>new HistoricalIntakeReceiptStore({rootDir:tempRoot,filePath:resolve(root,'outside-receipts.jsonl')}),{code:'HISTORICAL_RECEIPT_STORE_PATH_ESCAPE'});});test('calibrator consumes accepted intake records without changing semantic graph',()=>{const base=buildWorkGraphs(complex);const calibrated=calibrateGraphs(base,receipt.accepted_records);for(const key of Object.keys(base)){assert.deepEqual(calibrated.graphs[key].work_units.map((x)=>x.work_unit_id),base[key].work_units.map((x)=>x.work_unit_id));assert.deepEqual(calibrated.graphs[key].work_units.map((x)=>x.risk_factors),base[key].work_units.map((x)=>x.risk_factors));assert.equal(calibrated.graphs[key].metadata.historical_calibration_changes_graph,false);}});
test('forecast engine consumes intake records while preserving explicit UNKNOWN observations',()=>{const result=engine.forecast({brief:complex,historyRecords:receipt.accepted_records});assert.equal(result.forecast.historical_data_status,'PARTIAL');assert.ok(result.forecast.expected_path.total_tokens>0);assert.equal(receipt.accepted_records.find((x)=>x.task_id==='fixture.night.calls-known').total_tokens,null);});
test('PricingSnapshotRef validates CURRENT, STALE, and UNKNOWN without price values',()=>{for(const fixture of [pricingCurrent,pricingStale,pricingUnknown])assert.equal(validatePricingSnapshotRef(fixture),fixture);assert.ok([pricingCurrent,pricingStale,pricingUnknown].every((fixture)=>fixture.metadata.contains_price_values===false));assert.equal(pricingUnknown.currency,null);});
test('invalid PricingSnapshotRef authority is rejected',()=>{assert.throws(()=>validatePricingSnapshotRef({...pricingCurrent,authority:'StarBench'}),{code:'PRICING_SNAPSHOT_REF_INVALID'});});
test('EntitlementSnapshotRef validates known and UNKNOWN remaining state',()=>{assert.equal(validateEntitlementSnapshotRef(entitlementCurrent),entitlementCurrent);assert.equal(validateEntitlementSnapshotRef(entitlementUnknown),entitlementUnknown);assert.deepEqual(entitlementUnknown.remaining_state,{status:'UNKNOWN',value:null,unit:null});});
test('UNKNOWN entitlement cannot contain invented remaining values',()=>{const value=structuredClone(entitlementUnknown);value.remaining_state.value=0;assert.throws(()=>validateEntitlementSnapshotRef(value),{code:'ENTITLEMENT_SNAPSHOT_REF_CONFLICT'});});
test('missing snapshots do not block token forecast and declare both dependencies',()=>{const result=engine.forecast({brief:risk});const binding=bindResourceSnapshots({resourceProposal:result.resources});assert.equal(binding.pricing.status,'PRICING_SNAPSHOT_REQUIRED');assert.equal(binding.entitlement.status,'ENTITLEMENT_SNAPSHOT_REQUIRED');assert.ok(result.forecast.expected_path.total_tokens>0);assert.equal(binding.ready_for_03_integration,true);});
test('current and stale PricingSnapshotRef freshness are preserved',()=>{const result=engine.forecast({brief:risk});assert.equal(bindResourceSnapshots({resourceProposal:result.resources,pricingSnapshot:pricingCurrent}).pricing.status,'BOUND_CURRENT');assert.equal(bindResourceSnapshots({resourceProposal:result.resources,pricingSnapshot:pricingStale}).pricing.status,'BOUND_STALE');});
test('UNKNOWN snapshots remain explicit rather than becoming current',()=>{const riskResult=engine.forecast({brief:risk});const complexResult=engine.forecast({brief:complex});assert.equal(bindResourceSnapshots({resourceProposal:riskResult.resources,pricingSnapshot:pricingUnknown}).pricing.status,'BOUND_UNKNOWN');assert.equal(bindResourceSnapshots({resourceProposal:complexResult.resources,entitlementSnapshot:entitlementUnknown}).entitlement.status,'BOUND_UNKNOWN');});
test('snapshot references must match the Resource Proposal',()=>{const result=engine.forecast({brief:risk});assert.throws(()=>bindResourceSnapshots({resourceProposal:result.resources,pricingSnapshot:{...pricingCurrent,snapshot_ref:'wrong-ref'}}),{code:'PRICING_SNAPSHOT_REF_MISMATCH'});});
test('subscription usage remains measurable and is never API-price converted',()=>{const result=engine.forecast({brief:complex});const binding=bindResourceSnapshots({resourceProposal:result.resources,entitlementSnapshot:entitlementCurrent});assert.ok(result.resources.subscription_quota.total_tokens>0);assert.equal(result.resources.subscription_quota.monetary_cost,null);assert.equal(result.resources.metadata.subscription_api_price_conversion,false);assert.equal(binding.separation_guards.subscription_api_price_conversion,false);assert.equal(binding.metadata.subscription_cost_computed,false);});
test('Forecast Explanation Audit reconciles every path and every call',()=>{const result=engine.forecast({brief:risk,historyRecords:receipt.accepted_records});const binding=bindResourceSnapshots({resourceProposal:result.resources,pricingSnapshot:pricingCurrent});const audit=buildForecastExplanationAudit({...result,snapshotBinding:binding});assert.equal(audit.paths.length,3);assert.ok(audit.paths.every((path)=>path.reconciled));assert.ok(audit.paths.flatMap((path)=>path.work_units).every((unit)=>unit.reconciled));assert.equal(audit.truthfulness.all_totals_reconciled,true);});
test('Forecast Audit explains conservative risk work and model role choices',()=>{const result=engine.forecast({brief:risk,historyRecords:receipt.accepted_records});const audit=buildForecastExplanationAudit({...result});const conservative=audit.paths.find((path)=>path.path_type==='CONSERVATIVE_PATH');assert.ok(conservative.risk_expansions.length>=risk.risk_constraints.length);assert.ok(conservative.work_units.some((unit)=>unit.path_role==='RISK_RESPONSE'));assert.ok(conservative.work_units.every((unit)=>unit.model_choice.basis.includes(unit.task_type)));});
test('Forecast Audit exposes historical evidence without replacing project semantics',()=>{const result=engine.forecast({brief:complex,historyRecords:receipt.accepted_records});const audit=buildForecastExplanationAudit({...result});assert.equal(audit.historical_calibration.graph_semantics_preserved,true);assert.equal(audit.historical_calibration.historical_average_forecast,false);assert.equal(audit.truthfulness.historical_observations_inferred,false);});
test('Copyable Summary can reference Forecast Audit without execution authority',()=>{const result=engine.forecast({brief:risk});const audit=buildForecastExplanationAudit({...result});const summary=appendAuditReferenceToSummary(result.copyable_summary,audit);assert.ok(summary.includes(audit.audit_id));assert.ok(summary.includes('逐 Work Unit / call component 可审计'));assert.equal(audit.truthfulness.automatic_execution,false);});
test('Night Goal implementation has zero business network and no provider control surface',async()=>{assert.equal(networkRequests,0);for(const file of ['historical-usage-validator.mjs','historical-usage-intake.mjs','resource-snapshot-consumer.mjs','forecast-explanation-audit.mjs']){const source=await readFile(join(root,'src','token-intelligence',file),'utf8');assert.doesNotMatch(source,/fetch\s*\(|https?:\/\/|process\.env|Authorization|chat\.completions|ExecutionHub|OpenCode/iu);assert.doesNotMatch(source,/price[_ -]per[_ -]token|Math\.random|percentile/iu);}});
test('LEGACY_SUMMARY is never accepted as a historical token observation',()=>{assert.equal(receipt.outcomes.at(-1).classification,'INVALID');assert.equal(receipt.truthfulness.legacy_summary_promoted,false);assert.ok(receipt.accepted_records.every((record)=>record.record_type==='HISTORICAL_TASK_USAGE'));});
test('all fixture source references remain inside StarBench',()=>{assert.ok(receipt.provenance.source_ref.startsWith('tests/fixtures/'));assert.ok(!receipt.provenance.source_ref.includes('..'));assert.ok(resolve(root,receipt.provenance.source_ref).startsWith(root));});