import assert from 'node:assert/strict';
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import test, { after } from 'node:test';
import { fileURLToPath } from 'node:url';
import { main } from '../scripts/starbench-workbench.mjs';
import { ForecastWorkbench } from '../src/token-intelligence/forecast-workbench.mjs';
import { compareForecastBundles, loadForecastBundle } from '../src/token-intelligence/forecast-comparator.mjs';
const root=dirname(dirname(fileURLToPath(import.meta.url))),fd=join(root,'tests','fixtures','token-intelligence'),tmp=join(root,'tests','.tmp-overnight-p7');after(()=>rm(tmp,{recursive:true,force:true}));
async function prepare(){await rm(tmp,{recursive:true,force:true});await mkdir(tmp,{recursive:true});const brief=JSON.parse(await readFile(join(fd,'project-simple.json'),'utf8'));brief.pricing_snapshot_ref='cli-price';brief.entitlement_snapshot_ref='cli-ent';await writeFile(join(tmp,'brief.json'),JSON.stringify(brief));const ref={schema_version:'0.1',record_type:'PRICING_SNAPSHOT_REF',snapshot_ref:'cli-price',authority:'03-01 AI资产成本',provider:'fixture-provider',model:'fixture-model',billing_mode:'API_TOKEN_BILLED',snapshot_version:'v1',snapshot_timestamp:'2026-08-13T00:00:00.000Z',freshness_status:'CURRENT',currency:'CNY',pricing_components_ref:'fixture',metadata:{source_class:'TEST_FIXTURE',contains_price_values:false}};await writeFile(join(tmp,'pricing-ref.json'),JSON.stringify(ref));const resolved={schema_version:'0.1',record_type:'RESOLVED_PRICING_SNAPSHOT',snapshot_ref:'cli-price',authority:'03-01 AI资产成本',provider:'fixture-provider',model:'fixture-model',model_class:'CHAT_REASONING',billing_mode:'API_TOKEN_BILLED',snapshot_version:'v1',snapshot_timestamp:'2026-08-13T00:00:00.000Z',freshness_status:'CURRENT',currency:'CNY',billing_unit_tokens:1000000,prices:{input:'2',cached_input:'0.5',output:'8',reasoning:'4'},metadata:{source_class:'TEST_FIXTURE'}};await writeFile(join(tmp,'resolved.json'),JSON.stringify(resolved));const ent=JSON.parse(await readFile(join(fd,'entitlement-snapshot-current.fixture.json'),'utf8'));ent.snapshot_ref='cli-ent';ent.remaining_state={status:'KNOWN',value:999,unit:'TASKS'};await writeFile(join(tmp,'entitlement.json'),JSON.stringify(ent));return{brief,resolved,ent};}
test('Forecast CLI consumes explicit Snapshot files into complete budget bundle',async()=>{await prepare();const code=await main(['forecast','--input','tests/.tmp-overnight-p7/brief.json','--output','tests/.tmp-overnight-p7/out','--pricing-ref','tests/.tmp-overnight-p7/pricing-ref.json','--resolved-pricing','tests/.tmp-overnight-p7/resolved.json','--entitlement','tests/.tmp-overnight-p7/entitlement.json'],{rootDir:root});assert.equal(code,0);const dirs=await readdir(join(tmp,'out')),dir=join(tmp,'out',dirs[0]),budget=JSON.parse(await readFile(join(dir,'ai-resource-budget.json'),'utf8'));assert.equal(budget.api_resource.pricing.status,'CALCULATED');assert.equal(budget.subscription_resource.entitlement.status,'SUFFICIENT');assert.equal(budget.guards.automatic_quota_consumption,false)});
test('Forecast CLI consumes canonical Historical Usage without changing semantic core',async()=>{await prepare();const history=(await readFile(join(fd,'historical-usage-known.jsonl'),'utf8')).split(/\r?\n/u).filter(Boolean).map(JSON.parse);for(const record of history){record.provenance.source_class='IMPORTED_HISTORY';record.source='test imported history';record.metadata.fixture_only=false;}await writeFile(join(tmp,'history.jsonl'),history.map(JSON.stringify).join('\n'));const code=await main(['forecast','--input','tests/.tmp-overnight-p7/brief.json','--output','tests/.tmp-overnight-p7/history-out','--history-store','tests/.tmp-overnight-p7/history.jsonl'],{rootDir:root});assert.equal(code,0);const dirs=await readdir(join(tmp,'history-out')),forecast=JSON.parse(await readFile(join(tmp,'history-out',dirs[0],'forecast.json'),'utf8'));assert.notEqual(forecast.historical_data_status,'EMPTY');assert.equal(forecast.prediction_method.historical_average_times_task_count,false)});
test('missing external files fail before bundle output',async()=>{await prepare();await assert.rejects(main(['forecast','--input','tests/.tmp-overnight-p7/brief.json','--output','tests/.tmp-overnight-p7/missing-out','--resolved-pricing','tests/.tmp-overnight-p7/missing.json'],{rootDir:root}),{code:'ENOENT'});await assert.rejects(readdir(join(tmp,'missing-out')),{code:'ENOENT'})});
test('Snapshot CLI paths are root bounded',async()=>{await prepare();await assert.rejects(main(['forecast','--input','tests/.tmp-overnight-p7/brief.json','--output','tests/.tmp-overnight-p7/out','--resolved-pricing','../outside.json'],{rootDir:root}),{code:'WORKBENCH_CLI_PATH_ESCAPE'})});
test('CLI source contains no 03 authority data acquisition or network client',async()=>{const s=await readFile(join(root,'scripts','starbench-workbench.mjs'),'utf8');assert.doesNotMatch(s,/fetch\s*\(|https?:\/\/|process\.env|--activate|chat\.completions/iu)});
test('added CLI remains read-only to supplied Historical and Snapshot files',async()=>{const s=await readFile(join(root,'scripts','starbench-workbench.mjs'),'utf8');assert.ok(s.includes('readJsonl'));assert.ok(s.includes('readJson'));assert.doesNotMatch(s,/writeFile\(.*history_store|writeFile\(.*pricing_ref|writeFile\(.*resolved_pricing|writeFile\(.*entitlement/iu)});
test('Forecast compare explains pricing changes with zero Token delta',async()=>{const {brief,resolved,ent}=await prepare(),wb=new ForecastWorkbench(),input=JSON.stringify(brief),ref=JSON.parse(await readFile(join(tmp,'pricing-ref.json'),'utf8')),a=wb.run({input,pricingSnapshot:ref,resolvedPricingSnapshot:resolved,entitlementSnapshot:ent}).bundle,b=wb.run({input,pricingSnapshot:ref,resolvedPricingSnapshot:{...resolved,prices:{...resolved.prices,output:'12'}},entitlementSnapshot:ent}).bundle,d=compareForecastBundles(a,b);assert.notEqual(a.manifest.run_id,b.manifest.run_id);assert.equal(d.status,'CHANGED');assert.ok(d.paths.every(x=>x.token_delta===0));assert.ok(d.resource_assessment_changes.some(x=>x.field==='pricing'));});
test('bundle loader reads new assessment and remains compatible when optional file is absent',async()=>{await prepare();const wb=new ForecastWorkbench(),b=wb.run({input:await readFile(join(tmp,'brief.json'),'utf8')}).bundle,w=await wb.writeBundle(b,{rootDir:root,outputDir:join(tmp,'load-out')}),loaded=await loadForecastBundle(w.directory);assert.equal(loaded.resource_assessment.assessment_id,b.resource_assessment.assessment_id);await rm(join(w.directory,'resource-assessment.json'));const legacy=await loadForecastBundle(w.directory);assert.equal(legacy.resource_assessment,null)});