import assert from 'node:assert/strict';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import test, { after } from 'node:test';
import { fileURLToPath } from 'node:url';
import { ForecastWorkbench } from '../src/token-intelligence/forecast-workbench.mjs';
import { buildHistoricalCaseCatalog, explainCalibrationCases, searchHistoricalCases } from '../src/token-intelligence/historical-case-catalog.mjs';
import { backtestForecast, createForecastActualLink } from '../src/token-intelligence/forecast-backtest.mjs';
import { main } from '../scripts/starbench-workbench.mjs';
const root=dirname(dirname(fileURLToPath(import.meta.url))),fixtures=join(root,'tests','fixtures','token-intelligence'),tmp=join(root,'tests','.tmp-overnight-p3');
const readJsonl=async path=>(await readFile(path,'utf8')).split(/\r?\n/u).filter(Boolean).map(JSON.parse);
const seeds=await readJsonl(join(root,'data','historical-usage','historical-task-usage-seeds.jsonl'));
const fixtureRecords=await readJsonl(join(fixtures,'historical-usage-known.jsonl'));
const canonical=structuredClone(fixtureRecords[0]);canonical.provenance.source_class='IMPORTED_HISTORY';canonical.source='test imported history';canonical.metadata.fixture_only=false;
const partial=structuredClone(canonical);partial.usage_record_id=`usage_${'c'.repeat(64)}`;partial.total_tokens=null;
const brief=JSON.parse(await readFile(join(fixtures,'project-simple.json'),'utf8'));brief.project_id='starbench';brief.project_name='StarBench backtest fixture';
const wb=new ForecastWorkbench(),bundle=wb.run({input:JSON.stringify(brief)}).bundle,actual=seeds[0];
const link=createForecastActualLink({forecastManifest:bundle.manifest,actualRecord:actual,scope:{type:'PROJECT_TOTAL',project_id:'starbench'}});
after(()=>rm(tmp,{recursive:true,force:true}));
test('canonical imported observation is task comparable',()=>{const c=buildHistoricalCaseCatalog({canonicalRecords:[canonical]});assert.equal(c.cases[0].quality,'TASK_COMPARABLE');assert.equal(c.metadata.average_forecast,false)});
test('user-confirmed seeds remain project-scale only',()=>{const c=buildHistoricalCaseCatalog({seedRecords:seeds});assert.ok(c.cases.every(x=>x.quality==='PROJECT_SCALE_ONLY'));assert.ok(c.cases.every(x=>x.record_type==='HISTORICAL_TASK_USAGE_SEED'))});
test('canonical unknown total is partial context',()=>{assert.equal(buildHistoricalCaseCatalog({canonicalRecords:[partial]}).cases[0].quality,'PARTIAL_CONTEXT')});
test('test fixtures are explicitly ineligible',()=>{const c=buildHistoricalCaseCatalog({canonicalRecords:fixtureRecords});assert.ok(c.cases.every(x=>x.quality==='INELIGIBLE'&&x.quality_reason==='TEST_FIXTURE'))});
test('invalid history is ineligible rather than inferred',()=>{assert.equal(buildHistoricalCaseCatalog({canonicalRecords:[{record_type:'HISTORICAL_TASK_USAGE'}]}).cases[0].quality,'INELIGIBLE')});
test('search is deterministic and exposes field match reasons',()=>{const c=buildHistoricalCaseCatalog({canonicalRecords:[canonical],seedRecords:seeds}),q={project_id:'starbench',module:'04-01-StarBench',task_type:'PROJECT_GOAL_EXECUTION'};const a=searchHistoricalCases(c,q),b=searchHistoricalCases(c,q);assert.deepEqual(a,b);assert.ok(a[0].match_reasons.includes('MATCH:project_id'));assert.ok(a.every(x=>x.quality!=='INELIGIBLE'))});
test('seed retrieval never changes its evidence quality',()=>{const c=buildHistoricalCaseCatalog({seedRecords:seeds}),r=searchHistoricalCases(c,{project_id:'starbench'});assert.ok(r.length===5&&r.every(x=>x.quality==='PROJECT_SCALE_ONLY'))});
test('calibration explanation separates selected and excluded cases',()=>{const c=buildHistoricalCaseCatalog({canonicalRecords:[canonical,...fixtureRecords],seedRecords:seeds}),x=explainCalibrationCases(c,{project_id:'starbench'});assert.equal(x.historical_average_forecast,false);assert.ok(x.selected.length>0);assert.ok(x.excluded.some(y=>y.reason==='TEST_FIXTURE'))});
test('explicit project-total link records no automatic matching',()=>{assert.equal(link.metadata.explicit_link,true);assert.equal(link.metadata.automatic_matching,false);assert.equal(link.scope.type,'PROJECT_TOTAL')});
test('link creation rejects mismatched project scope',()=>{assert.throws(()=>createForecastActualLink({forecastManifest:bundle.manifest,actualRecord:actual,scope:{type:'PROJECT_TOTAL',project_id:'other'}}),{code:'BACKTEST_SCOPE_MISMATCH'})});
test('backtest reports signed absolute and percentage error without mutation',()=>{const before=JSON.stringify(bundle),result=backtestForecast({bundle,actualRecord:actual,link});assert.equal(result.signed_error_tokens,result.predicted_tokens-result.actual_tokens);assert.equal(result.absolute_error_tokens,Math.abs(result.signed_error_tokens));assert.equal(result.absolute_percentage_error,result.absolute_error_tokens/result.actual_tokens);assert.equal(result.metadata.historical_average_forecast,false);assert.equal(JSON.stringify(bundle),before)});
test('backtest rejects missing explicit link',()=>{assert.throws(()=>backtestForecast({bundle,actualRecord:actual,link:null}),{code:'BACKTEST_LINK_REQUIRED'})});
test('backtest rejects unknown actual token total',()=>{const unknown={...actual,total_tokens:null};assert.throws(()=>backtestForecast({bundle,actualRecord:unknown,link}),{code:'BACKTEST_ACTUAL_UNKNOWN'})});
test('zero actual produces unknown percentage instead of division artifact',()=>{const zero={...actual,total_tokens:0};const zlink={...link,actual_usage_record_id:zero.usage_record_id};const result=backtestForecast({bundle,actualRecord:zero,link:zlink});assert.equal(result.absolute_percentage_error,null);assert.equal(result.percentage_status,'UNKNOWN_ACTUAL_ZERO')});
test('CLI history-search consumes real seed store without manufacturing records',async()=>{assert.equal(await main(['history-search','--seed-store','data/historical-usage/historical-task-usage-seeds.jsonl','--query','{"project_id":"starbench"}','--limit','1'],{rootDir:root}),0)});
test('CLI backtest consumes an explicit link and writes only local result',async()=>{await rm(tmp,{recursive:true,force:true});await mkdir(tmp,{recursive:true});const out=join(tmp,'bundles');await wb.writeBundle(bundle,{rootDir:root,outputDir:out});await writeFile(join(tmp,'actual.json'),JSON.stringify(actual));await writeFile(join(tmp,'link.json'),JSON.stringify(link));assert.equal(await main(['backtest','--bundle',join(out,bundle.manifest.run_id),'--actual',join(tmp,'actual.json'),'--link',join(tmp,'link.json'),'--output',join(tmp,'result.json')],{rootDir:root}),0);const saved=JSON.parse(await readFile(join(tmp,'result.json'),'utf8'));assert.equal(saved.link_id,link.link_id)});
test('Phase 3 source cannot execute providers or invent average forecasts',async()=>{for(const name of ['historical-case-catalog.mjs','forecast-backtest.mjs']){const source=await readFile(join(root,'src','token-intelligence',name),'utf8');assert.doesNotMatch(source,/Math\.random|Monte Carlo|fetch\s*\(|https?:\/\/|process\.env|chat\.completions|--activate|average\s*\*|percentile/iu)}});
