"""Provider-neutral Automation Domain Contract V0.1."""

from .models import (
    CONTRACT_VERSION,
    AutomationEvidence,
    AutomationProvider,
    AutomationRun,
    AutomationStatus,
    AutomationTrigger,
    AutomationWorkflow,
    EvidenceAuthority,
    EvidenceKind,
    EvidenceRef,
    Provenance,
    ProviderCapability,
    ProviderMetadata,
    ProviderRef,
    RunRef,
    StatusScope,
    StatusValue,
    TriggerRef,
    TriggerType,
    WorkflowRef,
    serialize_contract,
    to_primitive,
)

__all__ = [
    "CONTRACT_VERSION",
    "AutomationEvidence",
    "AutomationProvider",
    "AutomationRun",
    "AutomationStatus",
    "AutomationTrigger",
    "AutomationWorkflow",
    "EvidenceAuthority",
    "EvidenceKind",
    "EvidenceRef",
    "Provenance",
    "ProviderCapability",
    "ProviderMetadata",
    "ProviderRef",
    "RunRef",
    "StatusScope",
    "StatusValue",
    "TriggerRef",
    "TriggerType",
    "WorkflowRef",
    "serialize_contract",
    "to_primitive",
]
