'use strict';const test=require('node:test');const assert=require('node:assert/strict');const os=require('node:os');const path=require('node:path');const fs=require('node:fs/promises');const {HardwareHistoryReadAPI,HardwareTelemetryHistoryStore,JsonHardwareTelemetryHistoryStore,METRICS,compactLargeHardwareHistory,gpuMetricName,projectHardwareTelemetry}=require('../src');
const AT='2026-08-13T00:00:00.000Z';function snap(at=AT,id='1'){const available=(v,u)=>({availability:'available',current:{value:v,unit:u},reason:null});return{snapshot_id:id,completed_at:at,system:{cpu:{availability:'available',utilization:{value:20,unit:'percent'}},memory:{availability:'available',utilization:{value:40,unit:'percent'}},gpu:{availability:'unsupported',utilization:null},temperatures:[{availability:'unavailable',current:null}],disks:[{volume_id:'C:',availability:'available',utilization:{value:50,unit:'percent'}}]},network:{traffic:{upload_rate:available(1,'bytes_per_second'),download_rate:available(2,'bytes_per_second')}},health:{status:'healthy'}};}
test('hardware projection has distinct semantics',()=>assert.equal(projectHardwareTelemetry(snap()).semantics,'hardware_telemetry_observation'));
test('hardware projection preserves CPU RAM and host traffic',()=>{const e=projectHardwareTelemetry(snap());assert.equal(e.metrics[METRICS.CPU].value,20);assert.equal(e.metrics[METRICS.NETWORK_DOWNLOAD].value,2);});
test('unavailable GPU and temperature remain null',()=>{const e=projectHardwareTelemetry(snap());assert.equal(e.metrics[METRICS.GPU].value,null);assert.equal(e.metrics[METRICS.TEMPERATURE].value,null);});
test('approved resident GPU observation feeds the existing history instead of the unsupported snapshot placeholder',()=>{const e=projectHardwareTelemetry(snap(),{gpuObservation:{availability:'available',utilization:{value:22,unit:'percent'},provider:'windows-gpu-engine-counter'}});assert.equal(e.metrics[METRICS.GPU].value,22);assert.equal(e.optional.gpu_provider,'windows-gpu-engine-counter');});
test('physical GPU utilization has an independent bounded history metric',async()=>{const id='dxgi-00000000-00000001',s=new HardwareTelemetryHistoryStore({now:()=>new Date(AT)}),entry=projectHardwareTelemetry(snap(),{gpuObservation:{availability:'available',utilization:{value:22,unit:'percent'},provider:'windows-dxgi-performance-counters',adapters:[{gpuId:id,utilization:{availability:'available',value:17,unit:'percent'}}]}});await s.append(entry);const value=await new HardwareHistoryReadAPI({store:s}).get_metric_history(gpuMetricName(id),AT,AT,{resolution:'raw'});assert.equal(value.latest,17);assert.equal(value.unit,'percent');});
test('store deduplicates and returns latest',async()=>{const s=new HardwareTelemetryHistoryStore({now:()=>new Date(AT)});await s.append(projectHardwareTelemetry(snap()));await s.append(projectHardwareTelemetry(snap()));assert.equal((await s.listWindow(AT,AT,{resolution:'raw'})).length,1);});
test('30 day retention removes older rows',async()=>{const s=new HardwareTelemetryHistoryStore({now:()=>new Date(AT)});await s.append(projectHardwareTelemetry(snap('2026-07-01T00:00:00Z')));assert.equal(await s.latest(),null);});
test('one hour window downsamples to minute buckets',async()=>{const s=new HardwareTelemetryHistoryStore({now:()=>new Date(AT)});await s.append(projectHardwareTelemetry(snap(AT,'1')));await s.append(projectHardwareTelemetry(snap('2026-08-13T00:00:01Z','2')));assert.equal((await s.listWindow(AT,'2026-08-13T01:00:00Z')).length,1);});
test('24 hour window uses five minute buckets',async()=>{const s=new HardwareTelemetryHistoryStore({now:()=>new Date(AT)});await s.append(projectHardwareTelemetry(snap(AT,'1')));await s.append(projectHardwareTelemetry(snap('2026-08-13T00:04:00Z','2')));assert.equal((await s.listWindow(AT,'2026-08-14T00:00:00Z')).length,1);});
test('JSON history restarts cleanly',async()=>{const d=await fs.mkdtemp(path.join(os.tmpdir(),'nexa-hw-'));const f=path.join(d,'h.json');try{await new JsonHardwareTelemetryHistoryStore({filePath:f,now:()=>new Date(AT)}).append(projectHardwareTelemetry(snap()));assert.equal((await new JsonHardwareTelemetryHistoryStore({filePath:f,now:()=>new Date(AT)}).latest()).snapshot_id,'1');}finally{await fs.rm(d,{recursive:true,force:true});}});
test('large persisted hardware history keeps recent raw data and tiered long-term evidence',()=>{const now=Date.parse(AT);const entries=Array.from({length:5001},(_,index)=>projectHardwareTelemetry(snap(new Date(now-(5000-index)*5000).toISOString(),String(index))));const compacted=compactLargeHardwareHistory(entries,now);assert.ok(compacted.length<entries.length);assert.equal(compacted.at(-1).snapshot_id,'5000');assert.ok(compacted.filter(entry=>Date.parse(entry.observed_at)>=now-60*60e3).length>=720);});
test('Read API creates UI-ready metric series',async()=>{const s=new HardwareTelemetryHistoryStore({now:()=>new Date(AT)});await s.append(projectHardwareTelemetry(snap()));const v=await new HardwareHistoryReadAPI({store:s}).get_metric_history(METRICS.CPU,AT,AT,{resolution:'raw'});assert.equal(v.unit,'percent');assert.equal(v.latest,20);assert.equal(v.availability,'available');});
test('unsupported metric is rejected',async()=>{const s=new HardwareTelemetryHistoryStore();await assert.rejects(()=>new HardwareHistoryReadAPI({store:s}).get_metric_history('ai.usage',AT,AT),/metric invalid/);});
