'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
const {ACPI_SCRIPT,NVIDIA_TEMPERATURE_ARGS,DeviceCenterReadAPI,DeviceHealthEvaluator,DeviceObservationRuntime,HardwareHistoryReadAPI,JsonHardwareTelemetryHistoryStore,METRICS,TemperatureObservationCache,TemperatureSensorService,WindowsGpuCollector,WindowsHardwareTemperatureCollector,buildDeviceOverviewViewModel,deduplicateSensors,normalizeSensor,parseAcpiThermalZones,parseNvidiaTemperatureCsv,projectHardwareTelemetry,selectPrimarySensor,temperatureView,validTemperature}=require('../src');
const {loadScenario}=require('../fixtures/scenarios');const AT='2026-08-13T05:00:00.000Z';
const sensor=(o={})=>({sensor_id:'gpu:nvidia:0:core',component:'gpu',sensor_name:'Fixture GPU Core',temperature_celsius:62,availability:'available',source:'fixture-vendor',observed_at:AT,confidence:'high',sensor_class:'gpu_core',current:{value:62,unit:'celsius'},freshness:{state:'fresh',age_ms:0,stale_after_ms:300000},reason:null,...o});
const observation=(s=[sensor()])=>({schema_version:'0.1',availability:'partial',sensors:s,providers:[{id:'fixture-vendor',availability:'available'}],observed_at:AT,duration_ms:12,reason:null,network_requests:0,admin_required:false});
const snapshot=()=>{const x=loadScenario('healthy_device');x.completed_at=AT;x.snapshot_id='temp-1';x.system.temperatures=[{sensor_id:'windows-temperature',source:'windows-system',availability:'unavailable',current:null,reason:'Unavailable.'}];return x;};

test('valid GPU temperature normalizes',()=>assert.equal(normalizeSensor(sensor()).temperature_celsius,62));
test('valid CPU temperature retains CPU identity',()=>assert.equal(normalizeSensor(sensor({sensor_id:'cpu:package',component:'cpu',sensor_class:'cpu_package'})).component,'cpu'));
test('lower provider range boundary is valid',()=>assert.equal(validTemperature(-100),true));
test('upper provider range boundary is valid',()=>assert.equal(validTemperature(250),true));
test('below provider range is rejected',()=>assert.equal(validTemperature(-101),false));
test('above provider range is rejected',()=>assert.equal(validTemperature(251),false));
test('unavailable sensor does not normalize to zero',()=>assert.equal(normalizeSensor({...sensor(),availability:'unavailable',temperature_celsius:0}),null));
test('malformed sensor is ignored',()=>assert.equal(normalizeSensor({temperature_celsius:'bad'}),null));
test('missing sensor identity is ignored',()=>assert.equal(normalizeSensor({...sensor(),sensor_id:''}),null));
test('unknown component remains explicit',()=>assert.equal(normalizeSensor({...sensor(),component:'mystery'}).component,'unknown'));
test('NVIDIA CSV is high-confidence GPU core',()=>{const x=parseNvidiaTemperatureCsv('0, Fixture GPU, 62',AT)[0];assert.equal(x.component,'gpu');assert.equal(x.confidence,'high');assert.equal(x.sensor_class,'gpu_core');});
test('NVIDIA malformed CSV is ignored',()=>assert.equal(parseNvidiaTemperatureCsv('private,invalid',AT).length,0));
test('NVIDIA CLI query requests only safe fields',()=>{assert.deepEqual(NVIDIA_TEMPERATURE_ARGS,['--query-gpu=index,name,temperature.gpu','--format=csv,noheader,nounits']);assert.doesNotMatch(NVIDIA_TEMPERATURE_ARGS.join(' '),/serial|uuid|power|account/i);});
test('ACPI zone converts deci-Kelvin to Celsius',()=>{const x=parseAcpiThermalZones(JSON.stringify({ObservedAt:AT,Items:[{InstanceName:'TZ00',CurrentTemperature:3200}]}),AT)[0];assert.equal(x.temperature_celsius,46.85);});
test('ACPI zone never becomes CPU',()=>assert.equal(parseAcpiThermalZones(JSON.stringify({ObservedAt:AT,Items:[{InstanceName:'CPU-like TZ',CurrentTemperature:3200}]}),AT)[0].component,'acpi_zone'));
test('ACPI zone confidence remains low',()=>assert.equal(parseAcpiThermalZones(JSON.stringify({ObservedAt:AT,Items:[{InstanceName:'TZ00',CurrentTemperature:3200}]}),AT)[0].confidence,'low'));
test('invalid ACPI JSON returns no sensors',()=>assert.deepEqual(parseAcpiThermalZones('bad',AT),[]));
test('multiple sensors are retained deterministically',()=>assert.deepEqual(deduplicateSensors([sensor({sensor_id:'gpu:b'}),sensor({sensor_id:'gpu:a'})]).map(x=>x.sensor_id),['gpu:a','gpu:b']));
test('duplicate sensor keeps higher confidence',()=>assert.equal(deduplicateSensors([sensor({confidence:'low'}),sensor({confidence:'high',temperature_celsius:63})])[0].temperature_celsius,63));
test('primary selection prefers confidence over heat',()=>assert.equal(selectPrimarySensor([sensor({confidence:'low',temperature_celsius:90}),sensor({sensor_id:'gpu:high',confidence:'high',temperature_celsius:60})],'gpu').sensor_id,'gpu:high'));
test('primary selection is component-specific',()=>assert.equal(selectPrimarySensor([sensor(),sensor({sensor_id:'cpu:package',component:'cpu'})],'cpu').component,'cpu'));

test('GPU temperature provider returns an observation',async()=>{const c=new WindowsGpuCollector({platform:'win32',now:()=>new Date(AT),monotonic:(()=>{let n=0;return()=>n+=5;})(),temperatureProvider:async()=>({stdout:'0, Fixture GPU, 62',stderr:''})});const x=await c.collectTemperatureSensors();assert.equal(x.availability,'available');assert.equal(x.sensors[0].temperature_celsius,62);});
test('GPU temperature failure is sanitized',async()=>{const c=new WindowsGpuCollector({platform:'win32',now:()=>new Date(AT),temperatureProvider:async()=>{throw new Error('credential secret')}});const x=await c.collectTemperatureSensors();assert.equal(x.availability,'unavailable');assert.doesNotMatch(JSON.stringify(x),/credential secret/);});
test('GPU utilization survives temperature failure',async()=>{const c=new WindowsGpuCollector({platform:'win32',now:()=>new Date(AT),provider:async()=>({stdout:JSON.stringify({ObservedAt:AT,SampleCount:1,Utilization:7}),stderr:''}),temperatureProvider:async()=>{throw new Error('fail')}});await c.collectTemperatureSensors();assert.equal((await c.collect()).utilization.value,7);});
test('collector tolerates partial GPU provider failure',async()=>{const c=new WindowsHardwareTemperatureCollector({platform:'win32',now:()=>new Date(AT),monotonic:()=>1,gpuCollector:{collectTemperatureSensors:async()=>{throw new Error('fail')}},acpiProvider:async()=>({stdout:JSON.stringify({ObservedAt:AT,Items:[{InstanceName:'TZ00',CurrentTemperature:3200}]}),stderr:''})});const x=await c.collect();assert.equal(x.availability,'partial');assert.equal(x.sensors[0].component,'acpi_zone');});
test('collector tolerates partial ACPI failure',async()=>{const c=new WindowsHardwareTemperatureCollector({platform:'win32',now:()=>new Date(AT),monotonic:()=>1,gpuCollector:{collectTemperatureSensors:async()=>({availability:'available',sensors:[sensor()]})},acpiProvider:async()=>{throw new Error('fail')}});assert.equal((await c.collect()).sensors[0].component,'gpu');});
test('total provider failure is unavailable not zero',async()=>{const c=new WindowsHardwareTemperatureCollector({platform:'win32',now:()=>new Date(AT),monotonic:()=>1,gpuCollector:{collectTemperatureSensors:async()=>{throw new Error('fail')}},acpiProvider:async()=>{throw new Error('fail')}});const x=await c.collect();assert.equal(x.availability,'unavailable');assert.equal(x.sensors.length,0);});

test('cache hit returns fresh value without provider',()=>{const c=new TemperatureObservationCache({now:()=>new Date(AT)});c.set(observation());assert.equal(c.get().cache.state,'fresh');});
test('cache marks old value stale',()=>{let now=new Date(AT);const c=new TemperatureObservationCache({now:()=>now,ttlMs:1000,staleRetentionMs:5000});c.set(observation());now=new Date(Date.parse(AT)+2000);assert.equal(c.get().sensors[0].freshness.state,'stale');});
test('cache expires value to unavailable',()=>{let now=new Date(AT);const c=new TemperatureObservationCache({now:()=>now,ttlMs:1000,staleRetentionMs:2000});c.set(observation());now=new Date(Date.parse(AT)+3000);assert.equal(c.get().availability,'unavailable');});
test('service current does not invoke collector',()=>{let calls=0;const service=new TemperatureSensorService({collector:{collect:async()=>{calls++;return observation();}},cache:new TemperatureObservationCache({now:()=>new Date(AT)})});service.current();assert.equal(calls,0);});
test('service observe writes cache',async()=>{const service=new TemperatureSensorService({collector:{collect:async()=>observation()},cache:new TemperatureObservationCache({now:()=>new Date(AT)})});await service.observe();assert.equal(service.current().sensors.length,1);});
test('slow runtime integrates temperature service',async()=>{let calls=0;const service=new TemperatureSensorService({collector:{collect:async()=>{calls++;return observation();}},cache:new TemperatureObservationCache({now:()=>new Date(AT)})});const r=new DeviceObservationRuntime({slowTask:service.slowTask()});await r.run('slow');assert.equal(calls,1);});
test('slow runtime failure is isolated',async()=>{const r=new DeviceObservationRuntime({slowTask:async()=>{throw new Error('secret')}});assert.equal(await r.run('slow'),null);assert.equal(r.status().errors.slow,'OBSERVATION_FAILED');});
test('slow runtime clean shutdown waits sensor query',async()=>{let release;const wait=new Promise(r=>release=r);const runtime=new DeviceObservationRuntime({slowTask:async()=>wait});runtime.run('slow');const done=runtime.shutdown();release();await done;assert.equal(runtime.status().in_flight.length,0);});

test('Device Center displays GPU temperature',()=>assert.equal(buildDeviceOverviewViewModel({snapshot:snapshot(),temperatureObservation:observation()}).temperatures.gpu.value,62));
test('Device Center keeps CPU temperature unavailable',()=>assert.equal(buildDeviceOverviewViewModel({snapshot:snapshot(),temperatureObservation:observation()}).temperatures.cpu.value,null));
test('Device Center never fabricates zero Celsius',()=>assert.notEqual(buildDeviceOverviewViewModel({snapshot:snapshot(),temperatureObservation:{sensors:[]}}).temperature.value,0));
test('Device Center exposes ACPI under other sensors',()=>{const zone=sensor({sensor_id:'acpi:tz00',component:'acpi_zone',confidence:'low',sensor_class:'acpi_thermal_zone'});assert.equal(temperatureView(observation([zone])).other[0].component,'acpi_zone');});
test('Device Center provider consumes cached observation',async()=>{const api=new DeviceCenterReadAPI({snapshotProvider:snapshot,temperatureProvider:()=>observation()});assert.equal((await api.get_overview()).temperatures.gpu.value,62);});
test('temperature ViewModel is deterministic',()=>assert.deepEqual(temperatureView(observation([sensor()])),temperatureView(observation([sensor()]))));

test('history writes GPU temperature independently',()=>assert.equal(projectHardwareTelemetry(snapshot(),{temperatureObservation:observation()}).metrics[METRICS.GPU_TEMPERATURE].value,62));
test('history keeps CPU temperature unavailable',()=>assert.equal(projectHardwareTelemetry(snapshot(),{temperatureObservation:observation()}).metrics[METRICS.CPU_TEMPERATURE].value,null));
test('temperature curve has Celsius unit',async()=>{const entry=projectHardwareTelemetry(snapshot(),{temperatureObservation:observation()});const store={listWindow:async()=>[entry]};const curve=await new HardwareHistoryReadAPI({store}).get_metric_history(METRICS.GPU_TEMPERATURE,AT,AT);assert.equal(curve.unit,'celsius');assert.equal(curve.latest,62);});
test('temperature history reopens from existing store',async(t)=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'nexa-temp-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const file=path.join(dir,'h.json'),entry=projectHardwareTelemetry(snapshot(),{temperatureObservation:observation()});await new JsonHardwareTelemetryHistoryStore({filePath:file,now:()=>new Date(AT)}).append(entry);const latest=await new JsonHardwareTelemetryHistoryStore({filePath:file,now:()=>new Date(AT)}).latest();assert.equal(latest.metrics[METRICS.GPU_TEMPERATURE].value,62);});

test('high-confidence GPU temperature enters health',()=>{const hot=observation([sensor({temperature_celsius:90,current:{value:90,unit:'celsius'}})]);const x=new DeviceHealthEvaluator({now:()=>new Date(AT)}).evaluate(snapshot(),{temperatureObservation:hot});assert.equal(x.reasons.some(r=>r.code==='GPU_TEMPERATURE_WARNING'),true);});
test('low-confidence ACPI is ignored by health',()=>{const zone=observation([sensor({component:'acpi_zone',confidence:'low',temperature_celsius:120,current:{value:120,unit:'celsius'}})]);const x=new DeviceHealthEvaluator({now:()=>new Date(AT)}).evaluate(snapshot(),{temperatureObservation:zone});assert.equal(x.reasons.some(r=>/TEMPERATURE/.test(r.code)),false);});
test('stale high-confidence sensor is ignored by health',()=>{const stale=observation([sensor({temperature_celsius:120,current:{value:120,unit:'celsius'},freshness:{state:'stale',age_ms:400000,stale_after_ms:300000}})]);const x=new DeviceHealthEvaluator({now:()=>new Date(AT)}).evaluate(snapshot(),{temperatureObservation:stale});assert.equal(x.reasons.some(r=>/TEMPERATURE/.test(r.code)),false);});
test('CPU metrics remain healthy when temperature is unavailable',()=>assert.equal(new DeviceHealthEvaluator({now:()=>new Date(AT)}).evaluate(snapshot(),{temperatureObservation:{sensors:[]}}).reasons.some(r=>/CPU_METRIC/.test(r.code)),false));
test('component thresholds are independently configurable',()=>{const e=new DeviceHealthEvaluator({now:()=>new Date(AT),policy:{temperature:{gpu:{warning_celsius:50,critical_celsius:60}}}});const x=e.evaluate(snapshot(),{temperatureObservation:observation()});assert.equal(x.reasons.some(r=>r.code==='GPU_TEMPERATURE_CRITICAL'),true);});

test('ACPI source is read-only and non-admin',()=>{assert.match(ACPI_SCRIPT,/Get-CimInstance/);assert.doesNotMatch(ACPI_SCRIPT,/Set-|Remove-|Start-Process|runas|Credential/i);});
test('temperature implementation contains no network client',async()=>{const code=await fs.readFile(path.join(__dirname,'..','src','hardwareTemperature.js'),'utf8');assert.doesNotMatch(code,/https?:\/\/|fetch\(|axios|http\.request|https\.request|net\.connect/);});
test('temperature observation records zero network and no admin',()=>{const x=observation();assert.equal(x.network_requests,0);assert.equal(x.admin_required,false);});
