'use strict';const test=require('node:test');const assert=require('node:assert/strict');const {GPU_INVENTORY_SCRIPT,GPU_SCRIPT,WindowsGpuCollector,parseGpuInventoryJson,parseGpuMetricsJson}=require('../src');const AT='2026-08-13T00:00:00Z';
test('GPU scripts are read-only bounded and profile-free',()=>{assert.match(GPU_SCRIPT,/Get-Counter/);assert.match(GPU_SCRIPT,/Microsoft\.PowerShell\.Diagnostics/);assert.match(GPU_INVENTORY_SCRIPT,/CreateDXGIFactory1/);assert.doesNotMatch(`${GPU_SCRIPT}\n${GPU_INVENTORY_SCRIPT}`,/Set-|Remove-|Start-Process|CommandLine/);});
test('GPU collector preserves genuine zero',async()=>{const c=new WindowsGpuCollector({platform:'win32',provider:async()=>({stdout:JSON.stringify({ObservedAt:AT,SampleCount:2,Utilization:0}),stderr:''})});assert.equal((await c.collect()).utilization.value,0);});
test('GPU collector returns finite utilization',async()=>{const c=new WindowsGpuCollector({platform:'win32',provider:async()=>({stdout:JSON.stringify({ObservedAt:AT,SampleCount:2,Utilization:5.5}),stderr:''})});assert.equal((await c.collect()).availability,'available');});
test('GPU collector fail-softs without a fake zero',async()=>{const c=new WindowsGpuCollector({platform:'win32',provider:async()=>{throw new Error('secret')}});const v=await c.collect();assert.equal(v.utilization,null);assert.doesNotMatch(JSON.stringify(v),/secret/);});
test('DXGI inventory excludes software adapters and preserves physical identities',()=>{const value=parseGpuInventoryJson(JSON.stringify([{Name:'Discrete GPU',Luid:'0x00000000_0x00000001',DedicatedVideoMemory:8000,SharedSystemMemory:16000,VendorId:1,DeviceId:2,Flags:0},{Name:'Software GPU',Luid:'0x00000000_0x00000002',DedicatedVideoMemory:0,SharedSystemMemory:16000,VendorId:3,DeviceId:4,Flags:2}]));assert.equal(value.length,1);assert.equal(value[0].gpuId,'dxgi-00000000-00000001');});
test('performance counter parser keeps per-adapter zero distinct from unavailable',()=>{const value=parseGpuMetricsJson(JSON.stringify({ObservedAt:AT,Items:[{Luid:'0x00000000_0x00000001',EngineSampleCount:2,Utilization:0,DedicatedUsedBytes:2000,SharedUsedBytes:500}]}));assert.equal(value.items.get('0x00000000_0x00000001').utilization,0);});
test('performance counter parser accepts PowerShell single-item JSON shape',()=>{const value=parseGpuMetricsJson(JSON.stringify({ObservedAt:AT,Items:{Luid:'0x00000000_0x00000001',EngineSampleCount:1,Utilization:5,DedicatedUsedBytes:2000,SharedUsedBytes:500}}));assert.equal(value.items.size,1);});
test('collector joins two physical GPUs to independent utilization and memory',async()=>{let inventoryCalls=0;const inventoryProvider=async()=>{inventoryCalls++;return{stderr:'',stdout:JSON.stringify([{Name:'GPU A',Luid:'0x00000000_0x00000001',DedicatedVideoMemory:8000,SharedSystemMemory:16000,VendorId:1,DeviceId:2,Flags:0},{Name:'GPU B',Luid:'0x00000000_0x00000002',DedicatedVideoMemory:4000,SharedSystemMemory:16000,VendorId:3,DeviceId:4,Flags:0}])};};const metricsProvider=async()=>({stderr:'',stdout:JSON.stringify({ObservedAt:AT,Items:[{Luid:'0x00000000_0x00000001',EngineSampleCount:2,Utilization:12,DedicatedUsedBytes:2000,SharedUsedBytes:500},{Luid:'0x00000000_0x00000002',EngineSampleCount:2,Utilization:0,DedicatedUsedBytes:1000,SharedUsedBytes:250}]})});const c=new WindowsGpuCollector({platform:'win32',inventoryProvider,metricsProvider,nowMs:()=>0});const first=await c.collect(),second=await c.collect();assert.equal(first.adapters.length,2);assert.equal(first.adapters[0].utilization.value,12);assert.equal(first.adapters[1].utilization.value,0);assert.equal(first.adapters[0].dedicatedMemory.used.value,2000);assert.equal(first.adapters[1].sharedMemory.used.value,250);assert.equal(first.utilization.value,12);assert.equal(inventoryCalls,1);assert.equal(second.adapters.length,2);});
