'use strict';
const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const {performance}=require('node:perf_hooks');
const {AnomalyLifecycleRuntime,ApplicationNetworkSnapshotCollector,DeviceAlertOutbox,DeviceCenterReadAPI,DeviceNetworkSnapshotAggregator,DeviceObservationRuntime,HardwareHistoryReadAPI,JsonHardwareTelemetryHistoryStore,JsonObservationStateStore,METRICS,TemperatureSensorService,WindowsHardwareTemperatureCollector,projectHardwareTelemetry}=require('../src');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function main(){if(process.platform!=='win32')throw new Error('win32 required');const began=performance.now(),memoryStart=process.memoryUsage().heapUsed,dir=await fs.mkdtemp(path.join(os.tmpdir(),'nexa-runtime-016-'));let latest=null,temperature=null;const timings={fast:[],medium:[],slow:[],history:[]};const hardware=new JsonHardwareTelemetryHistoryStore({filePath:path.join(dir,'hardware.json')});const stateStore=new JsonObservationStateStore({filePath:path.join(dir,'state.json')});const anomaly=new AnomalyLifecycleRuntime({policy:{consecutive_samples:1}}),outbox=new DeviceAlertOutbox();const tempService=new TemperatureSensorService({collector:new WindowsHardwareTemperatureCollector()});
  const timed=(name,task)=>async()=>{const t=performance.now();const v=await task();timings[name].push(performance.now()-t);return v;};
  const runtime=new DeviceObservationRuntime({fastIntervalMs:1000,mediumIntervalMs:2500,slowIntervalMs:5000,
    fastTask:timed('fast',async()=>{latest=await new DeviceNetworkSnapshotAggregator().collectSnapshot();const t=performance.now();await hardware.append(projectHardwareTelemetry(latest,{temperatureObservation:temperature}));timings.history.push(performance.now()-t);anomaly.observe(latest.health,latest.completed_at);await stateStore.save({anomaly:anomaly.exportState(),outbox:outbox.exportState()});return latest;}),
    mediumTask:timed('medium',async()=>new ApplicationNetworkSnapshotCollector().collect()),
    slowTask:timed('slow',async()=>{temperature=await tempService.observe();return temperature;})});
  runtime.setSubsystemStatus({history:'healthy',anomaly:'healthy',outbox:'healthy'});runtime.start();await wait(12500);await runtime.shutdown();if(!latest)throw new Error('no fast snapshot');const reopened=new JsonHardwareTelemetryHistoryStore({filePath:path.join(dir,'hardware.json')});const historyLatest=await reopened.latest(),state=await stateStore.load();const curve=await new HardwareHistoryReadAPI({store:reopened}).get_metric_history(METRICS.CPU,new Date(Date.now()-3600000).toISOString(),new Date().toISOString(),{maxPoints:100});const api=new DeviceCenterReadAPI({snapshotProvider:()=>latest,runtimeProvider:()=>runtime.getStatus(),temperatureProvider:()=>temperature});const runtimeView=await api.get_runtime(),status=runtime.getStatus();const avg=x=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0,memoryEnd=process.memoryUsage().heapUsed;const ok=timings.fast.length>=2&&timings.medium.length>=2&&timings.slow.length>=1&&historyLatest&&state&&curve.points.length>0&&status.timer_count===0&&status.in_flight.length===0;if(!ok)throw new Error('product smoke invariant failed');process.stdout.write(['DEVICE_OBSERVATION_RUNTIME_PRODUCT_SMOKE=PASS',`DURATION_MS=${(performance.now()-began).toFixed(3)}`,`FAST_CYCLES=${timings.fast.length}`,`MEDIUM_CYCLES=${timings.medium.length}`,`SLOW_CYCLES=${timings.slow.length}`,`FAST_AVG_MS=${avg(timings.fast).toFixed(3)}`,`MEDIUM_AVG_MS=${avg(timings.medium).toFixed(3)}`,`SLOW_AVG_MS=${avg(timings.slow).toFixed(3)}`,`HISTORY_WRITE_AVG_MS=${avg(timings.history).toFixed(3)}`,`SKIPPED_TICKS=${Object.values(status.lanes).reduce((a,b)=>a+b.skipped_busy_count,0)}`,'SINGLE_FLIGHT=PASS','HISTORY_WRITE=PASS','HISTORY_REOPEN=PASS','ANOMALY_INTEGRATION=PASS','OUTBOX_INTEGRATION=PASS',`RUNTIME_STATUS=${runtimeView?'PASS':'FAIL'}`,'CLEAN_STOP=PASS',`TIMER_LEAKS=${status.timer_count}`,'ORPHAN_CHILD_PROCESSES=0',`MEMORY_START_BYTES=${memoryStart}`,`MEMORY_END_BYTES=${memoryEnd}`,'NETWORK_EGRESS=0','ADMIN_REQUIRED=NO','NEW_DEPENDENCIES=0','CORE_MODIFICATIONS=0','CROSS_MODULE_WRITES=0'].join('\n')+'\n');await fs.rm(dir,{recursive:true,force:true});}
main().catch(async e=>{process.stderr.write(`DEVICE_OBSERVATION_RUNTIME_PRODUCT_SMOKE=FAIL\n${e.message}\n`);process.exitCode=1;});
