'use strict';
const {isIP}=require('node:net');
const {projectApexBindingViewModel}=require('./apexRouteBinding');
const {selectPrimarySensor}=require('./hardwareTemperature');
const {HISTORY_WINDOWS,SAFE_ACTIONS,anomalyDTO,applicationsDTO,buildDiagnosticsDTO,buildRecoveryViewModel,maskIp,metric,safeContract,severityForHealth}=require('./deviceCenterProduct');
const {METRICS,gpuMetricName}=require('./hardwareTelemetryHistory');
const {classifyDeviceCapability,classifyLocalDataState}=require('./deviceCapabilityState');
const clone=value=>value==null?value:JSON.parse(JSON.stringify(value));
const capacity=x=>x?.availability==='available'?{availability:'available',total:clone(x.total),used:clone(x.used),available:clone(x.available),utilization:clone(x.utilization),reason:null}:{availability:x?.availability||'unavailable',total:null,used:null,available:null,utilization:null,reason:x?.reason||'DATA_UNAVAILABLE'};
function projectGpuAdapters(observation){return(Array.isArray(observation?.adapters)?observation.adapters:[]).flatMap(adapter=>{if(typeof adapter?.gpuId!=='string'||!/^dxgi-[0-9a-f]{8}-[0-9a-f]{8}$/.test(adapter.gpuId)||typeof adapter?.name!=='string'||!adapter.name.trim())return[];const utilization=adapter.utilization?.availability==='available'&&Number.isFinite(adapter.utilization.value)&&adapter.utilization.value>=0&&adapter.utilization.value<=100?{availability:'available',value:adapter.utilization.value,unit:'percent',reason:null}:unavailable('percent',adapter.utilization?.reason||'GPU_UTILIZATION_COUNTER_UNAVAILABLE');return[{gpu_id:adapter.gpuId,name:adapter.name.trim().slice(0,120),utilization,dedicated_memory:capacity(adapter.dedicatedMemory),shared_memory:capacity(adapter.sharedMemory)}];}).slice(0,4);}
function unavailable(unit=null,reason='Capability is unavailable.'){return{availability:'unavailable',value:null,unit,reason};}
function measurement(block,field,unit){if(block?.availability!=='available')return unavailable(unit,block?.reason||'Metric unavailable.');const value=field?block[field]?.value:block.current?.value;return Number.isFinite(value)?{availability:'available',value,unit,reason:null}:unavailable(unit);}
const safeIpList=(values,family)=>[...new Set((Array.isArray(values)?values:[]).filter(value=>typeof value==='string'&&isIP(value)===family))].slice(0,16);
function projectLocalIdentity(value){const source=value?.local_identity||value||{},ipv4=safeIpList(source.ipv4||source.active_local_ipv4,4),ipv6=safeIpList(source.ipv6||source.active_local_ipv6,6),observedAt=Number.isFinite(Date.parse(source.observed_at))?source.observed_at:null;return{availability:ipv4.length||ipv6.length?'available':'unavailable',ipv4,ipv6,observed_at:observedAt};}
function safeApex(apex){return apex?.component_map?projectApexBindingViewModel(apex):(apex?clone(apex):{availability:'unavailable',route_model:'unknown'});}
function localValue(availability,value,reason=null,options={}){return{availability,value,reason,data_state:classifyLocalDataState({availability,reason,...options})};}
function presenceValue(value){return typeof value==='boolean'?localValue('available',value):localValue('unavailable',null,'PRESENCE_DATA_UNAVAILABLE');}
function projectNetworkRoutes(interfaces=[],apex={}){
  const byIndex=new Map(interfaces.filter(x=>Number.isInteger(x.interface_index)).map(x=>[x.interface_index,x]));
  const routes=(apex?.routes?.default_routes||apex?.defaultRoutes||[]).map(route=>{
    const adapter=byIndex.get(route.interface_index)||null;
    return{
      family:route.family||'ipv4',interface_index:route.interface_index??null,
      interface_name:adapter?.name||null,adapter_class:adapter?.adapter_class||'unknown',
      operational_status:adapter?.status||'unknown',next_hop_masked:route.next_hop_masked||null,
      route_metric:Number.isFinite(route.route_metric)?route.route_metric:null,
      recent_upload_rate:Number.isFinite(adapter?.recent_upload_rate)?adapter.recent_upload_rate:null,
      recent_download_rate:Number.isFinite(adapter?.recent_download_rate)?adapter.recent_download_rate:null
    };
  });
  routes.sort((left,right)=>{
    const leftUp=String(left.operational_status).toLowerCase()==='up'?0:1,rightUp=String(right.operational_status).toLowerCase()==='up'?0:1;
    if(leftUp!==rightUp)return leftUp-rightUp;
    const metric=(left.route_metric??Number.MAX_SAFE_INTEGER)-(right.route_metric??Number.MAX_SAFE_INTEGER);
    if(metric)return metric;
    return((right.recent_upload_rate||0)+(right.recent_download_rate||0))-((left.recent_upload_rate||0)+(left.recent_download_rate||0));
  });
  const primary=routes.find(route=>String(route.operational_status).toLowerCase()==='up')||null;
  return{availability:routes.length?'available':'unavailable',observed_at:apex?.observed_at||apex?.observedAt||null,selection_basis:'default_route_then_metric_then_recent_traffic',primary,items:routes};
}
function cpuTopology(cpu={}){const available=cpu.availability==='available';return{availability:available?'available':'unavailable',logical_processors:available&&Number.isInteger(cpu.logical_processors)?cpu.logical_processors:null,physical_cores:available&&Number.isInteger(cpu.physical_cores)?cpu.physical_cores:null,logical_data_state:classifyLocalDataState({availability:available&&Number.isInteger(cpu.logical_processors)?'available':'unavailable',reason:cpu.reason}),physical_data_state:classifyLocalDataState({availability:available&&Number.isInteger(cpu.physical_cores)?'available':'unavailable',reason:cpu.reason}),reason:available?null:(cpu.reason||'CPU_TOPOLOGY_UNAVAILABLE')};}
function buildRuntimeSummary(status){const value=status||{state:'stopped',lanes:{}};const lane=name=>{const x=value.lanes?.[name];return x?{status:x.status,freshness:x.freshness,last_success:x.last_success,consecutive_failures:x.consecutive_failures,skipped_busy_count:x.skipped_busy_count}:{status:'unsupported',freshness:'unavailable',last_success:null,consecutive_failures:0,skipped_busy_count:0};};return{schema_version:'0.1',state:value.state||'stopped',monitoring:value.state==='running'?'normal':(value.state==='degraded'?'degraded':'stopped'),started_at:value.started_at||null,last_recovery_event:value.last_recovery_event||null,lanes:{fast:lane('fast'),medium:lane('medium'),slow:lane('slow')},history_status:value.history_status||'unknown',anomaly_status:value.anomaly_engine_status||'unknown',alert_outbox_status:value.alert_outbox_status||'unknown',unsupported_capabilities:{application_network_bytes:'deferred_with_strong_evidence',cpu_temperature:'unavailable_with_evidence',apex_route:'unknown_with_strong_evidence'}};}
function temperatureView(observation,snapshotSensors=[]){const sensors=observation?.sensors?.length?observation.sensors:snapshotSensors;const cpu=selectPrimarySensor(sensors,'cpu'),gpu=selectPrimarySensor(sensors,'gpu');const available=(sensors||[]).filter(x=>x.availability==='available');const state=available.length?(cpu&&gpu?'available':'partial'):'unavailable';const item=x=>x?{availability:'available',value:x.temperature_celsius??x.current?.value,unit:'celsius',sensor_name:x.sensor_name||x.sensor_id,confidence:x.confidence||'low',freshness:x.freshness?.state||'unknown',reason:null}:unavailable('celsius');return{availability:state,cpu:item(cpu),gpu:item(gpu),other:available.filter(x=>x!==cpu&&x!==gpu).map(x=>({component:x.component,sensor_name:x.sensor_name||x.sensor_id,value:x.temperature_celsius??x.current?.value,unit:'celsius',confidence:x.confidence||'low',freshness:x.freshness?.state||'unknown'}))};}
function buildDeviceOverviewViewModel({snapshot,apex,egress,anomalies,gpuObservation,temperatureObservation,runtimeStatus}){const snapshotSensors=snapshot.system.temperatures||[];const temperatures=temperatureView(temperatureObservation,snapshotSensors);const legacy=snapshotSensors.find(x=>x.availability==='available');const temperature=temperatures.gpu.availability==='available'?temperatures.gpu:(temperatures.cpu.availability==='available'?temperatures.cpu:(legacy?measurement(legacy,null,'celsius'):unavailable('celsius','No supported temperature provider.')));const gpu=gpuObservation?.availability==='available'?{availability:'available',value:gpuObservation.utilization.value,unit:'percent',reason:null}:measurement(snapshot.system.gpu,'utilization','percent');return{schema_version:'0.1',observed_at:snapshot.completed_at,cpu:measurement(snapshot.system.cpu,'utilization','percent'),ram:measurement(snapshot.system.memory,'utilization','percent'),gpu,temperature,temperatures,runtime:buildRuntimeSummary(runtimeStatus),disks:snapshot.system.disks.map(d=>({id:d.volume_id,label:d.label||d.volume_id,utilization:measurement(d,'utilization','percent')})),network:{availability:snapshot.network.availability,upload:measurement(snapshot.network.traffic.upload_rate,null,'bytes_per_second'),download:measurement(snapshot.network.traffic.download_rate,null,'bytes_per_second')},public_ip:egress?.identity?.public_ip?{availability:'available',value:egress.identity.public_ip}:{availability:'unavailable',value:null},location:egress?.identity?.geo_availability==='available'?{availability:'available',country:egress.identity.country||null,region:egress.identity.region||null,city:egress.identity.city||null}:{availability:'unavailable',country:null,region:null,city:null},apex:safeApex(apex),health:clone(snapshot.health),active_anomaly_count:anomalies?.active?.length||0};}
function buildPerformanceViewModel(snapshot,temperatureObservation){const temperatures=temperatureView(temperatureObservation,snapshot.system.temperatures||[]);return{schema_version:'0.1',metrics:{cpu:measurement(snapshot.system.cpu,'utilization','percent'),ram:measurement(snapshot.system.memory,'utilization','percent'),gpu:measurement(snapshot.system.gpu,'utilization','percent'),temperature:temperatures.gpu.availability==='available'?temperatures.gpu:(temperatures.cpu.availability==='available'?temperatures.cpu:unavailable('celsius')),cpu_temperature:temperatures.cpu,gpu_temperature:temperatures.gpu}};}
class DeviceCenterReadAPI{
constructor(o={}){Object.assign(this,o);}latestSnapshot(){const s=this.snapshotProvider?.();if(!s)throw new Error('Device snapshot unavailable.');return s;}
runtimeStatus(){const value=typeof this.runtimeProvider==='function'?this.runtimeProvider():this.runtimeProvider;return value?.getStatus?value.getStatus():(value||null);}
async get_overview(){const gpuObservation=await Promise.resolve(this.gpuProvider?.());const view=buildDeviceOverviewViewModel({snapshot:this.latestSnapshot(),apex:await Promise.resolve(this.apexProvider?.()),egress:await Promise.resolve(this.egressProvider?.()),gpuObservation,temperatureObservation:await Promise.resolve(this.temperatureProvider?.()),runtimeStatus:await Promise.resolve(this.runtimeStatus()),anomalies:this.anomalyRuntime?.list()});view.gpu_adapters=projectGpuAdapters(gpuObservation);return view;}
async get_overview_product(){
  const snapshot=this.latestSnapshot(),base=await this.get_overview(),network=await this.get_network_product(),events=await this.get_anomalies_product(),freshness=base.runtime?.lanes?.fast?.freshness||'unknown';
  const disks=snapshot.system.disks.map(x=>({id:x.volume_id,label:x.label||x.volume_id,...capacity(x),health:x.availability!=='available'?'unknown':(x.utilization.value>=95?'critical':(x.utilization.value>=85?'warning':'healthy'))}));
  const host=snapshot.system.host||{availability:'unavailable'},cpu=snapshot.system.cpu||{availability:'unavailable'};
  const gpuName=base.temperatures.gpu?.sensor_name?String(base.temperatures.gpu.sensor_name).replace(/\s+GPU Core$/i,''):null;
  const capabilityStates={system:classifyDeviceCapability({collectorAvailable:host.availability==='available'||cpu.availability==='available',hasData:Boolean(snapshot.system)}),network:network.capability_states?.network||'NO_DATA',public_ip:network.capability_states?.public_ip||'SOURCE_NOT_CONFIGURED',cpu_temperature:'PERMISSION_UNSUPPORTED',freshness:classifyDeviceCapability({stale:freshness==='stale',partial:freshness==='unknown'})};
  const computerName=host.availability==='available'?localValue('available',host.name):localValue('unavailable',null,host.reason||'HOST_IDENTITY_UNAVAILABLE');
  const windowsVersion=host.availability==='available'?localValue('available',[host.version,host.release].filter(Boolean).join(' · ')):localValue('unavailable',null,host.reason||'HOST_IDENTITY_UNAVAILABLE');
  const windowsBuild=host.availability==='available'&&host.build?localValue('available',host.build):localValue('unavailable',null,host.reason||'WINDOWS_BUILD_UNAVAILABLE');
  const topology=cpuTopology(cpu);
  const cpuTemperature={availability:'unsupported',value:null,unit:'celsius',freshness:'unknown',reason:'CPU_TEMPERATURE_UNAVAILABLE_WITH_EVIDENCE',data_state:'UNSUPPORTED'};
  return{schema_version:'0.1',contract:'DeviceCenterOverviewDTO V0.1',availability:base.health?.status==='unknown'||Object.values(capabilityStates).some(x=>!['READY','PERMISSION_UNSUPPORTED'].includes(x))?'partial':'available',device_health:{status:base.health?.status||'unknown',severity:severityForHealth(base.health?.status),reason_count:base.health?.reasons?.length||0},computer_name:computerName,windows_version:windowsVersion,windows_build:windowsBuild,runtime_status:base.runtime,cpu:{...base.cpu,model:cpu.model||null},cpu_topology:topology,memory_capacity:capacity(snapshot.system.memory),ram:base.ram,gpu:{...base.gpu,model:gpuName},gpu_memory:capacity(snapshot.system.gpu?.memory),gpus:clone(base.gpu_adapters||[]),gpu_temperature:base.temperatures.gpu,cpu_temperature:cpuTemperature,disks,interfaces:clone(snapshot.network.interfaces||[]),network_connection:clone(snapshot.network.interface_summary||null),network_gateway_dns_presence:clone(network.gateway_dns_presence),total_upload:network.total_upload,total_download:network.total_download,network_availability:network.availability,domestic_path:network.domestic_path,foreign_path:network.foreign_path,public_ip:network.public_ip,approximate_location:network.approximate_location,apex:network.apex,capability_states:capabilityStates,local_data_states:{windows_build:windowsBuild.data_state,cpu_physical_cores:topology.physical_data_state,cpu_temperature:'UNSUPPORTED',network_gateway:network.gateway_dns_presence?.gateway?.data_state||'UNAVAILABLE',network_dns:network.gateway_dns_presence?.dns?.data_state||'UNAVAILABLE',network_probe:network.network_probe?.target_status==='not_configured'?'NOT_PROBED':'AVAILABLE'},active_anomaly_count:events.active.length,latest_critical_anomaly:events.active.find(x=>x.severity==='critical')||null,last_updated:base.observed_at,overall_freshness:freshness};
}
async get_runtime(){return buildRuntimeSummary(await Promise.resolve(this.runtimeStatus()));}
async get_performance(){const temperature=await Promise.resolve(this.temperatureProvider?.());const view=buildPerformanceViewModel(this.latestSnapshot(),temperature);const gpu=await Promise.resolve(this.gpuProvider?.());if(gpu?.availability==='available')view.metrics.gpu={availability:'available',value:gpu.utilization.value,unit:'percent',reason:null};view.gpus=projectGpuAdapters(gpu).map(adapter=>({gpu_id:adapter.gpu_id,name:adapter.name,current:adapter.utilization}));return view;}
async historyMetric(name,window='one_hour'){if(!Object.hasOwn(HISTORY_WINDOWS,window))throw new TypeError('history window invalid');if(!this.hardwareHistoryApi)return{schema_version:'0.1',metric:name,unit:null,points:[],availability:'unavailable',freshness:'unknown',observed_at:null,empty_state:{code:'NO_HISTORY_DATA'}};const end=this.latestSnapshot().completed_at,start=new Date(Date.parse(end)-HISTORY_WINDOWS[window]).toISOString();const value=await this.hardwareHistoryApi.get_metric_history(name,start,end,{maxPoints:300}),latest=value.points.at(-1)?.at||value.points.at(-1)?.observed_at||null,age=latest?Math.max(0,Date.parse(end)-Date.parse(latest)):null;return{...value,freshness:age===null?'unknown':(age<=300000?'fresh':'stale'),observed_at:latest,empty_state:value.points.length?null:{code:'NO_HISTORY_DATA'}};}
async get_performance_product({window='one_hour'}={}){const s=this.latestSnapshot(),base=await this.get_performance(),freshness=s.system.metadata?.freshness?.state||'unknown';const names={cpu:METRICS.CPU,ram:METRICS.RAM,gpu:METRICS.GPU,gpu_temperature:METRICS.GPU_TEMPERATURE,cpu_temperature:METRICS.CPU_TEMPERATURE,network_upload:METRICS.NETWORK_UPLOAD,network_download:METRICS.NETWORK_DOWNLOAD};const curves=Object.fromEntries(await Promise.all(Object.entries(names).map(async([k,v])=>[k,await this.historyMetric(v,window)])));const current=x=>({...x,freshness,observed_at:s.completed_at});const disks=s.system.disks.map(d=>({id:d.volume_id,usage:current(measurement(d,'utilization','percent')),history:{availability:'unavailable',points:[],unit:'percent',empty_state:{code:'DISK_HISTORY_NOT_SEPARATELY_AVAILABLE'}}}));const gpus=await Promise.all((base.gpus||[]).map(async adapter=>({gpu_id:adapter.gpu_id,name:adapter.name,current:current(adapter.current),history:await this.historyMetric(gpuMetricName(adapter.gpu_id),window)})));return{schema_version:'0.1',contract:'DevicePerformanceDTO V0.1',availability:'available',observed_at:s.completed_at,window,metrics:{cpu:{current:current(base.metrics.cpu),history:curves.cpu},ram:{current:current(base.metrics.ram),history:curves.ram},gpu:{current:current(base.metrics.gpu),history:curves.gpu},gpu_temperature:{current:current(base.metrics.gpu_temperature),history:curves.gpu_temperature},cpu_temperature:{current:{availability:'unsupported',value:null,unit:'celsius',freshness:'unknown',observed_at:s.completed_at,reason:'CPU_TEMPERATURE_UNAVAILABLE_WITH_EVIDENCE',data_state:'UNSUPPORTED'},history:curves.cpu_temperature},network_upload:{current:current(measurement(s.network.traffic.upload_rate,null,'bytes_per_second')),history:curves.network_upload},network_download:{current:current(measurement(s.network.traffic.download_rate,null,'bytes_per_second')),history:curves.network_download}},gpus,disks};}
async get_top_consumers(){const a=this.applicationSnapshotProvider?.();return a?{cpu:a.application_summary.cpu_top5.slice(0,5),ram:a.application_summary.ram_top5.slice(0,5),network:a.application_summary.network_top5.availability==='available'?a.application_summary.network_top5.items.slice(0,5):[],network_availability:a.application_summary.network_top5.availability}:{cpu:[],ram:[],network:[],network_availability:'unavailable'};}
async get_applications(){return applicationsDTO(await Promise.resolve(this.applicationSnapshotProvider?.()));}
async get_network(){const s=this.latestSnapshot();return{host:clone(s.network),paths:await Promise.resolve(this.pathViewProvider?.())||null,apex:safeApex(await Promise.resolve(this.apexProvider?.()))};}
async get_network_product(){
  const s=this.latestSnapshot(),paths=await Promise.resolve(this.pathViewProvider?.())||{},apex=safeApex(await Promise.resolve(this.apexProvider?.())),identity=await Promise.resolve(this.egressProvider?.())||{},localIdentity=await Promise.resolve(this.localNetworkIdentityProvider?.());
  const networkProbe=await Promise.resolve(this.networkProbeProvider?.())||{schema_version:'0.1',contract:'ApexNetworkProbeProduct V0.1',status:'target_pending',status_label:'探针待配置',target_status:'not_configured',target_count:0,targets:[],tiers:{light:{availability:'target_pending',execution_policy:'manual_or_low_frequency'},quality:{availability:'target_pending',execution_policy:'manual_or_low_frequency'},full:{availability:'target_pending',execution_policy:'user_initiated_only',background_bandwidth_saturation_allowed:false}},last_result:null,existing_apex_harness_reused:true,network_settings_modified:false};
  const i=identity.identity||identity,freshness=s.network.metadata?.freshness?.state||'unknown',decorate=x=>({...x,freshness,observed_at:s.completed_at}),summary=s.network.interface_summary||{};
  const networkState=classifyDeviceCapability({collectorAvailable:s.network.availability!=='unknown',networkReachable:s.network.availability!=='offline',hasData:Boolean(s.network.interface_summary),stale:freshness==='stale'}),egressConfigured=Boolean(identity.identity||identity.availability||identity.provider),publicIpState=classifyDeviceCapability({sourceConfigured:egressConfigured,hasData:Boolean(i.public_ip)});
  const domestic=paths.domestic||{status:'unavailable',latency:metric(null,'milliseconds',{availability:'unavailable',reason:'LATENCY_NOT_OBSERVED'}),last_verified_at:null},foreign=paths.foreign||{status:'deferred',latency:metric(null,'milliseconds',{availability:'unavailable',reason:'FOREIGN_PATH_DEFERRED'}),last_verified_at:null};
  const gatewayDnsPresence={gateway:presenceValue(summary.gateway_present),dns:presenceValue(summary.dns_present),local_address:presenceValue(summary.address_present),privacy:'presence_only_no_configuration_values'};
  const interfaces=clone(s.network.interfaces||[]),routeObservation=projectNetworkRoutes(interfaces,apex);
  return{schema_version:'0.1',contract:'DeviceNetworkDTO V0.1',availability:s.network.availability==='online'?'available':(s.network.availability==='unknown'?'partial':'unavailable'),observed_at:s.completed_at,total_upload:decorate(measurement(s.network.traffic.upload_rate,null,'bytes_per_second')),total_download:decorate(measurement(s.network.traffic.download_rate,null,'bytes_per_second')),interfaces,connection:{availability:s.network.availability,active_count:summary.active_count??0,primary:routeObservation.primary||clone(summary.primary||null)},default_routes:routeObservation,gateway_dns_presence:gatewayDnsPresence,local_ip:projectLocalIdentity(localIdentity||i.local_identity),public_ip:i.public_ip?{availability:'available',value:i.public_ip}:{availability:'unavailable',value:null,reason:egressConfigured?'NO_DATA':'SOURCE_NOT_CONFIGURED'},approximate_location:i.geo_availability==='available'?{availability:'available',country:i.country||null,region:i.region||null,city:i.city||null,isp:i.isp||null,asn:i.asn||null}:{availability:'unavailable',country:null,region:null,city:null,isp:null,asn:null},domestic_path:domestic,foreign_path:foreign,network_probe:clone(networkProbe),local_data_states:{gateway:gatewayDnsPresence.gateway.data_state,dns:gatewayDnsPresence.dns.data_state,local_address:gatewayDnsPresence.local_address.data_state,probe_target:networkProbe.target_status==='not_configured'?'NOT_PROBED':'AVAILABLE'},capability_states:{network:networkState,public_ip:publicIpState,domestic_path:paths.domestic?'READY':'SOURCE_NOT_CONFIGURED',foreign_path:paths.foreign?'READY':'SOURCE_NOT_CONFIGURED'},last_verified_at:s.completed_at,apex:{runtime:apex.availability||'unavailable',route_model:apex.route_model||'unknown',confidence:apex.confidence||'low',limited_visibility:(apex.route_model||'unknown')==='unknown'}};
}
async get_network_identity(){return clone(await Promise.resolve(this.egressProvider?.())||{availability:'unavailable'});}
async get_history(metric,start,end){return this.hardwareHistoryApi.get_metric_history(metric,start,end);}
async get_history_product({window='one_hour'}={}){if(!Object.hasOwn(HISTORY_WINDOWS,window))throw new TypeError('history window invalid');const names={cpu:METRICS.CPU,ram:METRICS.RAM,gpu:METRICS.GPU,gpu_temperature:METRICS.GPU_TEMPERATURE,cpu_temperature:METRICS.CPU_TEMPERATURE,network_upload:METRICS.NETWORK_UPLOAD,network_download:METRICS.NETWORK_DOWNLOAD};const metrics=Object.fromEntries(await Promise.all(Object.entries(names).map(async([k,v])=>[k,await this.historyMetric(v,window)])));const any=Object.values(metrics).some(x=>x.points.length);return{schema_version:'0.1',contract:'DeviceHistoryDTO V0.1',window,availability:any?'available':'unavailable',metrics,disks:{availability:'unavailable',points:[],unit:'percent',empty_state:{code:'DISK_HISTORY_NOT_SEPARATELY_AVAILABLE'}},empty_state:any?null:{code:'NO_HISTORY_DATA',message:'No history is available for this time window.'}};}
async get_anomalies(){return this.anomalyRuntime?.list()||{active:[],resolved:[]};}
async get_anomalies_product(){return anomalyDTO(await this.get_anomalies());}
async get_alerts({status,limit=100}={}){if(status&&!['pending','delivered','dismissed'].includes(status))throw new TypeError('alert status invalid');if(!Number.isInteger(limit)||limit<1||limit>100)throw new RangeError('alert limit invalid');if(!this.alertOutbox)return{schema_version:'0.1',availability:'unavailable',items:[],empty_state:{code:'ALERT_OUTBOX_UNAVAILABLE'},os_delivery:'cross_module_deferred'};const items=this.alertOutbox.list(status?{status}:{}).slice(0,limit).map(x=>({alert_id:x.alert_id,anomaly_id:x.anomaly_id,severity:x.severity,title:x.title,summary:x.summary,created_at:x.created_at,delivery_status:x.delivery_status}));return{schema_version:'0.1',availability:items.length?'available':'unavailable',items,empty_state:items.length?null:{code:'NO_ALERTS'},os_delivery:'cross_module_deferred'};}
async get_diagnostics(){const runtime=typeof this.runtimeProvider==='function'?this.runtimeProvider():this.runtimeProvider,diagnostics=runtime?.diagnostics?.()||null,history=this.historyStatusProvider?.()||this.hardwareHistoryApi?.store?.status?.()||{status:'unknown'},temperature=await Promise.resolve(this.temperatureProvider?.());const egress=await Promise.resolve(this.egressProvider?.())||{};return buildDiagnosticsDTO({runtimeDiagnostics:diagnostics,historyStatus:history.status,applicationStatus:this.applicationSnapshotProvider?.()?'healthy':'unavailable',sensorStatus:temperature?.sensors?.length?'healthy':'unavailable',networkStatus:this.latestSnapshot().network.availability==='unknown'?'degraded':'healthy',legacyStatus:this.latestSnapshot().legacy?.availability||'unavailable',apexStatus:(await Promise.resolve(this.apexProvider?.()))?.availability||'unavailable',outboxStatus:this.alertOutbox?'healthy':'unavailable',publicIp:(egress.identity||egress).public_ip||null});}
async get_recovery(){const runtime=await Promise.resolve(this.runtimeStatus())||{},history=this.historyStatusProvider?.()||this.hardwareHistoryApi?.store?.status?.()||{status:'unknown'},temperature=await Promise.resolve(this.temperatureProvider?.());return buildRecoveryViewModel({runtimeStatus:runtime,historyStatus:history.status,sensorStatus:temperature?.sensors?.length?'healthy':'unavailable',lastRecovery:runtime.last_recovery_event?this.latestSnapshot().completed_at:null});}
async get_dashboard_snapshot(){const [overview,applications,recovery]=await Promise.all([this.get_overview_product(),this.get_applications(),this.get_recovery()]);const anomalies=await this.get_anomalies_product();return{schema_version:'0.1',contract:'DEVICE_CENTER_PRODUCT_CONTRACT_V0_1',overview,top5:{cpu:applications.cpu_top5,ram:applications.ram_top5,network:applications.network_top5},latest_anomaly:anomalies.active[0]||anomalies.recent_resolved[0]||null,runtime:overview.runtime_status,recovery:{headline:recovery.headline,overall_state:recovery.overall_state,issue_count:recovery.issues.length},bounded:true};}
async execute_action(action,payload={}){if(!SAFE_ACTIONS.includes(action))throw new TypeError('recovery action is not allowed');const runtime=typeof this.runtimeProvider==='function'?this.runtimeProvider():this.runtimeProvider;if(action==='run_observation_once')return runtime?.runOnce?.(payload.lanes)||null;if(action==='restart_observation_runtime')return runtime?.restart?.()??null;if(action==='retry_failed_component')return runtime?.runOnce?.(payload.component||'fast')||null;if(action==='re_read_sensor')return this.temperatureService?.observe?.()||null;if(action==='clear_expired_cache'){this.temperatureService?.cache?.clear?.();return{status:'completed'};}if(action==='dismiss_alert')return this.alertOutbox?.ackDismissed(payload.alert_id)||null;if(action==='mark_alert_delivered')return this.alertOutbox?.ackDelivered(payload.alert_id)||null;if(action==='acknowledge_diagnostic'||action==='acknowledge_anomaly')return{status:'acknowledged',id:payload.diagnostic_id||payload.anomaly_id||null};if(action==='refresh_overview')return this.get_overview_product();if(action==='retry_history_reopen')return this.hardwareHistoryApi?.get_latest?.()||null;return null;}
async get_application_detail(appId){const a=this.applicationSnapshotProvider?.();if(!a)return{availability:'unavailable',empty_state:{code:'APPLICATION_OBSERVATION_NOT_STARTED'}};const item=a.applications.find(x=>x.application.application_id===appId);if(!item)return{availability:'unavailable',empty_state:{code:'APPLICATION_NOT_FOUND'}};const history=this.applicationHistoryApi?await this.applicationHistoryApi.getApplicationHistory(appId):{data:[]};return{schema_version:'0.1',contract:'ApplicationDetailDTO V0.1',availability:'available',application:clone(item.application),process_count:item.process_ids.length,process_group:{process_ids:clone(item.process_ids)},resources:{cpu:a.application_summary.cpu_top5.find(x=>x.application.application_id===appId)?.value??null,ram:a.application_summary.ram_top5.find(x=>x.application.application_id===appId)?.value??null},connections:{active:item.active_connection_count,protocols:clone(item.protocol_counts),remote_endpoint_summary:clone(item.remote_endpoints),semantics:'connection_activity_not_byte_usage'},traffic:item.traffic?clone(item.traffic):null,traffic_availability:item.traffic?'available':'unavailable',traffic_support:item.traffic?'supported':'not_supported_yet',traffic_reason:item.traffic?null:'APPLICATION_BYTE_ACCOUNTING_NOT_AVAILABLE',country_distribution:item.country_distribution?clone(item.country_distribution):[],history:history.data||[],history_empty_state:history.data?.length?null:{code:'NO_APPLICATION_HISTORY'},anomalies:(this.anomalyRuntime?.list().active||[]).filter(x=>x.component===appId)};}
get_product_contract(){return safeContract();}
}
module.exports={DeviceCenterReadAPI,buildDeviceOverviewViewModel,buildPerformanceViewModel,buildRuntimeSummary,projectNetworkRoutes,safeApex,temperatureView,unavailable};
