'use strict';

const {SCHEMA_VERSION}=require('./contracts');

const ProductAvailability=Object.freeze({AVAILABLE:'available',PARTIAL:'partial',UNAVAILABLE:'unavailable',UNSUPPORTED:'unsupported',DEFERRED:'deferred',UNKNOWN:'unknown'});
const ProductFreshness=Object.freeze({FRESH:'fresh',STALE:'stale',UNKNOWN:'unknown'});
const ProductSeverity=Object.freeze({INFO:'info',NORMAL:'normal',WARNING:'warning',CRITICAL:'critical',UNKNOWN:'unknown'});
const RecoveryState=Object.freeze({HEALTHY:'healthy',RECOVERING:'recovering',DEGRADED:'degraded',RECOVERED:'recovered',ACTION_REQUIRED:'action_required',UNAVAILABLE:'unavailable'});
const SAFE_ACTIONS=Object.freeze(['refresh_overview','run_observation_once','restart_observation_runtime','retry_failed_component','retry_history_reopen','clear_expired_cache','re_read_sensor','acknowledge_diagnostic','acknowledge_anomaly','dismiss_alert','mark_alert_delivered']);
const HISTORY_WINDOWS=Object.freeze({one_hour:60*60e3,one_day:24*60*60e3,seven_days:7*24*60*60e3,thirty_days:30*24*60*60e3});

function iso(value){return Number.isFinite(Date.parse(value))?new Date(value).toISOString():null;}
function metric(value,unit,{availability,freshness='unknown',observedAt=null,reason=null}={}){const present=Number.isFinite(value);return{availability:availability||(present?'available':'unavailable'),value:present?value:null,unit,freshness:Object.values(ProductFreshness).includes(freshness)?freshness:'unknown',observed_at:iso(observedAt),reason:present?null:(reason||'DATA_UNAVAILABLE')};}
function maskIp(value){if(typeof value!=='string')return null;if(value.includes(':'))return `${value.split(':').slice(0,2).join(':')}::x`;const parts=value.split('.');return parts.length===4?`${parts[0]}.${parts[1]}.x.x`:null;}
function severityForHealth(status){return({healthy:'normal',warning:'warning',critical:'critical',unknown:'unknown'})[status]||'unknown';}
function recoveryIssue(component,status,{detectedAt=null,title=null,summary=null,automatic=true,actionRequired=false,actions=[]}={}){const severity=status==='action_required'?'critical':(status==='degraded'?'warning':'info');return{component,severity,title:title||`${component} recovery status`,summary:summary||'The component is operating with a safe recovery state.',detected_at:iso(detectedAt),status,automatic_recovery_available:automatic,user_action_required:actionRequired,available_actions:actions.filter(x=>SAFE_ACTIONS.includes(x))};}
function runtimeRecovery(status={}){if(status.state==='failed')return recoveryIssue('observation_runtime','action_required',{summary:'Device monitoring could not start.',automatic:false,actionRequired:true,actions:['restart_observation_runtime']});if(status.state==='degraded')return recoveryIssue('observation_runtime','degraded',{summary:'Some monitoring components are temporarily unavailable.',actions:['retry_failed_component','restart_observation_runtime']});if(status.state==='starting')return recoveryIssue('observation_runtime','recovering',{summary:'Device monitoring is starting.'});if(status.state==='stopped'||!status.state)return recoveryIssue('observation_runtime','unavailable',{summary:'Device monitoring has not started.',actions:['restart_observation_runtime']});return null;}
function historyRecovery(status='unknown'){if(status==='recovered')return recoveryIssue('history','recovered',{summary:'Some history was unavailable; safe recovery mode is active.',actions:['retry_history_reopen']});if(status==='degraded')return recoveryIssue('history','degraded',{summary:'History is temporarily unavailable.',actions:['retry_history_reopen']});if(status==='unavailable'||status==='unknown')return recoveryIssue('history','unavailable',{summary:'History status is not available.',actions:['retry_history_reopen']});return null;}
function buildRecoveryViewModel({runtimeStatus,historyStatus='unknown',sensorStatus='unknown',lastRecovery=null}={}){const issues=[runtimeRecovery(runtimeStatus||{}),historyRecovery(historyStatus)];if(sensorStatus==='degraded'||sensorStatus==='unavailable')issues.push(recoveryIssue('gpu_sensor',sensorStatus==='degraded'?'degraded':'unavailable',{summary:'GPU temperature is temporarily unavailable; GPU utilization remains available.',actions:['re_read_sensor']}));const filtered=issues.filter(Boolean);const order={action_required:5,degraded:4,recovering:3,recovered:2,unavailable:1,healthy:0};const overall=filtered.sort((a,b)=>(order[b.status]||0)-(order[a.status]||0))[0]?.status||'healthy';return{schema_version:SCHEMA_VERSION,headline:overall==='healthy'?'Device monitoring is operating normally.':(overall==='recovered'?'Monitoring recovered safely.':'Some monitoring data needs attention.'),overall_state:overall,issues:filtered,automatic_actions:[...new Set(filtered.flatMap(x=>x.available_actions).filter(x=>!x.user_action_required))],manual_actions:filtered.filter(x=>x.user_action_required).flatMap(x=>x.available_actions),last_recovery:iso(lastRecovery)};}
function buildDiagnosticsDTO({runtimeDiagnostics,historyStatus='unknown',applicationStatus='unknown',sensorStatus='unknown',networkStatus='unknown',legacyStatus='unknown',apexStatus='unknown',outboxStatus='unknown',publicIp=null}={}){const rows=(runtimeDiagnostics?.components||[]).map(x=>({component:`runtime_${x.component}`,status:x.status,last_success:iso(x.last_success),freshness:x.last_success?'fresh':'unknown',failure_count:x.failure_count||0,safe_code:x.failure_code||null,safe_summary:x.failure_code?'Observation temporarily unavailable.':'Operating normally.'}));for(const [component,status] of [['history',historyStatus],['application_observatory',applicationStatus],['gpu_sensor',sensorStatus],['network_collector',networkStatus],['legacy_binding',legacyStatus],['apex_runtime',apexStatus],['alert_outbox',outboxStatus]])rows.push({component,status,last_success:null,freshness:'unknown',failure_count:status==='degraded'?1:0,safe_code:status==='degraded'?'COMPONENT_DEGRADED':null,safe_summary:['degraded','unavailable'].includes(status)?'Component data is temporarily limited.':'Operating normally.'});return{schema_version:SCHEMA_VERSION,status:rows.some(x=>x.status==='degraded')?'degraded':'healthy',public_ip_masked:maskIp(publicIp),components:rows};}
function anomalyDTO(events={active:[],resolved:[]},now=new Date()){const map=x=>({id:x.anomaly_id,type:x.type,severity:x.severity,component:x.component,status:x.state,started_at:x.first_seen,last_seen_at:x.last_seen,resolved_at:x.resolved_at||null,duration_ms:Math.max(0,(x.resolved_at?Date.parse(x.resolved_at):now.getTime())-Date.parse(x.first_seen)),summary:`${x.component} reported ${x.type}.`});return{schema_version:SCHEMA_VERSION,availability:(events.active?.length||events.resolved?.length)?'available':'unavailable',empty_state:(events.active?.length||events.resolved?.length)?null:{code:'NO_ANOMALIES',message:'No device anomalies have been recorded.'},active:(events.active||[]).map(map),recent_resolved:(events.resolved||[]).slice(-20).reverse().map(map)};}
function applicationsDTO(snapshot){if(!snapshot)return{schema_version:SCHEMA_VERSION,availability:'unavailable',cpu_top5:[],ram_top5:[],network_top5:{availability:'unavailable',reason:'APPLICATION_BYTE_ACCOUNTING_NOT_AVAILABLE',items:[]},top_active_connections:{availability:'unavailable',semantics:'connection_activity_not_byte_usage',items:[]},empty_state:{code:'APPLICATION_OBSERVATION_NOT_STARTED'}};const summary=snapshot.application_summary||{};const count=snapshot.active_application_count??snapshot.applications?.length??0;return{schema_version:SCHEMA_VERSION,availability:snapshot.availability||'available',cpu_top5:(summary.cpu_top5||[]).slice(0,5),ram_top5:(summary.ram_top5||[]).slice(0,5),network_top5:summary.network_top5?.availability==='available'?{availability:'available',reason:null,items:(summary.network_top5.items||[]).slice(0,5)}:{availability:'unavailable',reason:'APPLICATION_BYTE_ACCOUNTING_NOT_AVAILABLE',items:[]},top_active_connections:{availability:snapshot.connection_observation?.availability||'unavailable',semantics:'connection_activity_not_byte_usage',items:(summary.top_active_connections||[]).slice(0,5)},empty_state:count?null:{code:'NO_APPLICATION_OBSERVATIONS'}};}
function historyWindow(name){if(!Object.hasOwn(HISTORY_WINDOWS,name))throw new TypeError('history window invalid');return HISTORY_WINDOWS[name];}
function safeContract(){return{schema_version:SCHEMA_VERSION,contract:'DEVICE_CENTER_PRODUCT_CONTRACT_V0_1',screens:['overview','performance','network','applications','history','anomalies','diagnostics_recovery'],default_screen:'overview',safe_actions:[...SAFE_ACTIONS],dangerous_actions:[{action:'delete_history',availability:'hidden',confirmation_required:true},{action:'reset_store',availability:'hidden',confirmation_required:true}]};}

module.exports={HISTORY_WINDOWS,ProductAvailability,ProductFreshness,ProductSeverity,RecoveryState,SAFE_ACTIONS,anomalyDTO,applicationsDTO,buildDiagnosticsDTO,buildRecoveryViewModel,historyWindow,maskIp,metric,recoveryIssue,safeContract,severityForHealth};
