'use strict';
const {performance}=require('node:perf_hooks');
const RUNTIME_INTERVALS=Object.freeze({fast:5000,medium:30000,slow:300000});
const BACKGROUND_RUNTIME_INTERVALS=Object.freeze({fast:30000,medium:120000,slow:600000});
const RuntimeState=Object.freeze({STOPPED:'stopped',STARTING:'starting',RUNNING:'running',DEGRADED:'degraded',STOPPING:'stopping',FAILED:'failed'});
const ActivityMode=Object.freeze({FOREGROUND:'foreground',BACKGROUND:'background'});
const LANES=Object.freeze(['fast','medium','slow']);
function safeIso(value){const d=value instanceof Date?value:new Date(value);return Number.isFinite(d.getTime())?d.toISOString():new Date(0).toISOString();}
class DeviceObservationRuntime{
 constructor(o={}){this.fastTask=o.fastTask||null;this.mediumTask=o.mediumTask||o.applicationTask||null;this.applicationTask=this.mediumTask;this.slowTask=o.slowTask||null;this.foregroundIntervals={fast:o.fastIntervalMs??RUNTIME_INTERVALS.fast,medium:o.mediumIntervalMs??o.applicationIntervalMs??RUNTIME_INTERVALS.medium,slow:o.slowIntervalMs??RUNTIME_INTERVALS.slow};this.backgroundIntervals={fast:Math.max(o.backgroundFastIntervalMs??BACKGROUND_RUNTIME_INTERVALS.fast,this.foregroundIntervals.fast),medium:Math.max(o.backgroundMediumIntervalMs??BACKGROUND_RUNTIME_INTERVALS.medium,this.foregroundIntervals.medium),slow:Math.max(o.backgroundSlowIntervalMs??BACKGROUND_RUNTIME_INTERVALS.slow,this.foregroundIntervals.slow)};this.activityMode=o.activityMode??ActivityMode.FOREGROUND;this.schedule=o.setInterval||globalThis.setInterval;this.cancel=o.clearInterval||globalThis.clearInterval;this.now=o.now||(()=>new Date());this.monotonic=o.monotonic||(()=>performance.now());this.failureThreshold=o.failureThreshold??3;this.gapFactor=o.gapFactor??3;this.timers=new Map();this.flights=new Map();this.lanes=Object.fromEntries(LANES.map(x=>[x,{last_tick_at:null,last_success:null,last_duration_ms:null,consecutive_failures:0,total_failures:0,skipped_busy_count:0,gap_count:0,clock_jump_count:0,last_failure_code:null,last_recovery_event:null,last_wall_ms:null,last_mono_ms:null,cycles:0}]));this.state=RuntimeState.STOPPED;this.startedAt=null;this.stoppedAt=null;this.historyStatus='unknown';this.anomalyStatus='unknown';this.alertOutboxStatus='unknown';for(const value of [...Object.values(this.foregroundIntervals),...Object.values(this.backgroundIntervals)])if(!Number.isInteger(value)||value<10)throw new RangeError('runtime intervals must be >= 10ms');if(!Object.values(ActivityMode).includes(this.activityMode))throw new TypeError('activity mode is invalid');if(!Number.isInteger(this.failureThreshold)||this.failureThreshold<1)throw new RangeError('failureThreshold invalid');}
 task(layer){return layer==='medium'?this.mediumTask:this[`${layer}Task`];}
 intervalsFor(mode=this.activityMode){return mode===ActivityMode.BACKGROUND?this.backgroundIntervals:this.foregroundIntervals;}
 intervalFor(layer){return this.intervalsFor()[layer];}
 scheduleTimers({immediate=false}={}){for(const layer of LANES){if(!this.task(layer))continue;const timer=this.schedule(()=>{this.tick(layer);},this.intervalFor(layer));timer?.unref?.();this.timers.set(layer,timer);if(immediate)this.tick(layer);}}
 async run(layer,{tick=false}={}){if(!LANES.includes(layer))throw new TypeError('runtime lane invalid');const task=this.task(layer);if(!task)return null;const lane=this.lanes[layer];if(this.flights.has(layer)){if(tick)lane.skipped_busy_count++;return this.flights.get(layer);}const wall=this.now(),wallMs=wall.getTime(),mono=this.monotonic(),interval=this.intervalFor(layer);if(tick&&lane.last_wall_ms!==null){const wallDelta=wallMs-lane.last_wall_ms,monoDelta=mono-lane.last_mono_ms;if(wallDelta<0||Math.abs(wallDelta-monoDelta)>interval*2)lane.clock_jump_count++;if(monoDelta>interval*this.gapFactor){lane.gap_count++;lane.last_recovery_event='resumed_after_gap';}}lane.last_wall_ms=wallMs;lane.last_mono_ms=mono;lane.last_tick_at=safeIso(wall);const started=mono;const p=Promise.resolve().then(task).then(v=>{const recovered=lane.consecutive_failures>0;lane.consecutive_failures=0;lane.last_failure_code=null;lane.last_success=safeIso(this.now());lane.cycles++;if(recovered)lane.last_recovery_event='collector_recovered';return v;}).catch(()=>{lane.consecutive_failures++;lane.total_failures++;lane.last_failure_code='OBSERVATION_FAILED';return null;}).finally(()=>{lane.last_duration_ms=Math.max(0,this.monotonic()-started);this.flights.delete(layer);this.refreshState();});this.flights.set(layer,p);return p;}
 tick(layer){return this.run(layer,{tick:true});}
 async runOnce(layers=LANES){const selected=Array.isArray(layers)?layers:[layers];return Object.fromEntries(await Promise.all(selected.map(async x=>[x,await this.run(x)])));}
 start({immediate=true}={}){if(this.timers.size)return false;this.state=RuntimeState.STARTING;this.startedAt=safeIso(this.now());this.stoppedAt=null;this.scheduleTimers({immediate});this.refreshState();return true;}
 setActivityMode(mode){if(!Object.values(ActivityMode).includes(mode))throw new TypeError('activity mode is invalid');if(mode===this.activityMode)return false;this.activityMode=mode;if(!this.timers.size)return true;for(const timer of this.timers.values())this.cancel(timer);this.timers.clear();this.scheduleTimers({immediate:false});this.refreshState();return true;}
 stop(){if(!this.timers.size&&this.state===RuntimeState.STOPPED)return false;this.state=RuntimeState.STOPPING;for(const timer of this.timers.values())this.cancel(timer);this.timers.clear();this.stoppedAt=safeIso(this.now());if(!this.flights.size)this.state=RuntimeState.STOPPED;return true;}
 async restart(options={}){this.stop();await Promise.allSettled([...this.flights.values()]);this.state=RuntimeState.STOPPED;return this.start(options);}
 async shutdown(){this.stop();await Promise.allSettled([...this.flights.values()]);this.state=RuntimeState.STOPPED;}
 setSubsystemStatus({history,anomaly,outbox}={}){if(history)this.historyStatus=history;if(anomaly)this.anomalyStatus=anomaly;if(outbox)this.alertOutboxStatus=outbox;this.refreshState();}
 refreshState(){if(this.state===RuntimeState.STOPPING&&this.flights.size)return;if(!this.timers.size&&this.state!==RuntimeState.STARTING){if(this.state!==RuntimeState.STOPPING)return;}const degraded=LANES.some(x=>this.lanes[x].consecutive_failures>=this.failureThreshold)||[this.historyStatus,this.anomalyStatus,this.alertOutboxStatus].includes('degraded');this.state=this.timers.size?(degraded?RuntimeState.DEGRADED:RuntimeState.RUNNING):RuntimeState.STOPPED;}
 getStatus(){const nowMs=this.now().getTime(),intervals=this.intervalsFor(),lanes={};for(const name of LANES){const x=this.lanes[name],last=x.last_success?Date.parse(x.last_success):NaN;const age=Number.isFinite(last)?Math.max(0,nowMs-last):null;lanes[name]={status:x.consecutive_failures>=this.failureThreshold?'degraded':(this.task(name)?'ready':'unsupported'),last_tick_at:x.last_tick_at,last_success:x.last_success,last_duration_ms:x.last_duration_ms,freshness:age===null?'unavailable':(age<=intervals[name]*this.gapFactor?'fresh':'stale'),consecutive_failures:x.consecutive_failures,total_failures:x.total_failures,skipped_busy_count:x.skipped_busy_count,gap_count:x.gap_count,clock_jump_count:x.clock_jump_count,cycles:x.cycles,last_failure_code:x.last_failure_code,last_recovery_event:x.last_recovery_event};}return{schema_version:'0.1',state:this.state,running:this.timers.size>0,started_at:this.startedAt,stopped_at:this.stoppedAt,activity_mode:this.activityMode,intervals:{...intervals},foreground_intervals:{...this.foregroundIntervals},background_intervals:{...this.backgroundIntervals},in_flight:[...this.flights.keys()],lanes,history_status:this.historyStatus,anomaly_engine_status:this.anomalyStatus,alert_outbox_status:this.alertOutboxStatus,timer_count:this.timers.size,last_recovery_event:LANES.map(x=>this.lanes[x].last_recovery_event).filter(Boolean).at(-1)||null};}
 status(){const x=this.getStatus();return{...x,last_success:Object.fromEntries(LANES.flatMap(k=>x.lanes[k].last_success?[[k==='medium'?'application':k,x.lanes[k].last_success]]:[])),errors:Object.fromEntries(LANES.flatMap(k=>x.lanes[k].last_failure_code?[[k==='medium'?'application':k,x.lanes[k].last_failure_code]]:[]))};}
 diagnostics(){const s=this.getStatus();return{schema_version:'0.1',runtime_state:s.state,components:Object.entries(s.lanes).map(([component,x])=>({component,status:x.status,last_success:x.last_success,failure_code:x.last_failure_code,failure_count:x.consecutive_failures,skipped_busy_count:x.skipped_busy_count})),history:{status:s.history_status},anomaly:{status:s.anomaly_engine_status},alert_outbox:{status:s.alert_outbox_status}};}
}
module.exports={ActivityMode,BACKGROUND_RUNTIME_INTERVALS,DeviceObservationRuntime,LANES,RUNTIME_INTERVALS,RuntimeState};
