'use strict';
const {execFile}=require('node:child_process');
const path=require('node:path');
const {performance}=require('node:perf_hooks');
const {SCHEMA_VERSION}=require('./contracts');
const {WindowsGpuCollector}=require('./providers/windowsGpuCollector');
const TemperatureComponent=Object.freeze({CPU:'cpu',GPU:'gpu',MOTHERBOARD:'motherboard',STORAGE:'storage',ACPI_ZONE:'acpi_zone',OTHER:'other',UNKNOWN:'unknown'});
const TemperatureConfidence=Object.freeze({HIGH:'high',MEDIUM:'medium',LOW:'low'});
const TemperatureSensorClass=Object.freeze({CPU_PACKAGE:'cpu_package',CPU_CORE:'cpu_core',GPU_CORE:'gpu_core',ACPI_THERMAL_ZONE:'acpi_thermal_zone',OTHER:'other',UNKNOWN:'unknown'});
const ACPI_SCRIPT="$items=@(Get-CimInstance -Namespace root/wmi -ClassName MSAcpi_ThermalZoneTemperature -ErrorAction SilentlyContinue|ForEach-Object{[PSCustomObject]@{InstanceName=[string]$_.InstanceName;CurrentTemperature=$_.CurrentTemperature}});[PSCustomObject]@{ObservedAt=[DateTimeOffset]::UtcNow.ToString('o');Items=$items}|ConvertTo-Json -Depth 3 -Compress";
const TEMPERATURE_CAPABILITY_MATRIX=Object.freeze({gpu_utilization:{state:'ready',evidence:'windows-gpu-engine-counter'},gpu_temperature:{state:'ready',evidence:'nvidia-smi-if-present'},cpu_temperature:{state:'unavailable',evidence:'no identity-safe built-in provider'},acpi_thermal_zone:{state:'partial',evidence:'MSAcpi_ThermalZoneTemperature, never mapped to CPU'},other_sensors:{state:'deferred',evidence:'no installed identity-safe provider discovered'}});
function run(executable,args){return new Promise((resolve,reject)=>execFile(executable,args,{timeout:5000,windowsHide:true,encoding:'utf8',maxBuffer:1024*1024},(e,stdout,stderr)=>e?reject(e):resolve({stdout:String(stdout||''),stderr:String(stderr||'')})));}
function safeSensorName(value,fallback='Unknown sensor'){const text=String(value||'').trim().replace(/[\r\n\t]/g,' ');return text&&text.length<=160&&!/[<>]/.test(text)?text:fallback;}
function validTemperature(value){return Number.isFinite(value)&&value>=-100&&value<=250;}
function normalizeSensor(input,{staleAfterMs=300000}={}){const temperature=Number(input?.temperature_celsius??input?.current?.value);const component=Object.values(TemperatureComponent).includes(input?.component)?input.component:TemperatureComponent.UNKNOWN;const confidence=Object.values(TemperatureConfidence).includes(input?.confidence)?input.confidence:TemperatureConfidence.LOW;const sensorClass=Object.values(TemperatureSensorClass).includes(input?.sensor_class)?input.sensor_class:TemperatureSensorClass.UNKNOWN;const observedAt=new Date(input?.observed_at);const id=String(input?.sensor_id||'').trim().toLowerCase();if(!input||input.availability!=='available'||!id||!validTemperature(temperature)||!Number.isFinite(observedAt.getTime()))return null;return{schema_version:SCHEMA_VERSION,sensor_id:id.slice(0,160),component,sensor_name:safeSensorName(input.sensor_name),temperature_celsius:temperature,availability:'available',source:safeSensorName(input.source,'unknown').slice(0,80),observed_at:observedAt.toISOString(),freshness:{state:'fresh',age_ms:0,stale_after_ms:staleAfterMs},confidence,sensor_class:sensorClass,current:{value:temperature,unit:'celsius'},reason:null};}
function deduplicateSensors(values){const byId=new Map(),rank={low:1,medium:2,high:3};for(const input of values||[]){const sensor=normalizeSensor(input);if(!sensor)continue;const old=byId.get(sensor.sensor_id);if(!old||rank[sensor.confidence]>rank[old.confidence]||Date.parse(sensor.observed_at)>Date.parse(old.observed_at))byId.set(sensor.sensor_id,sensor);}return[...byId.values()].sort((a,b)=>a.component.localeCompare(b.component)||a.sensor_id.localeCompare(b.sensor_id));}
function parseAcpiThermalZones(stdout,fallbackAt){let value;try{value=JSON.parse(String(stdout||''));}catch{return[];}const observedAt=Number.isFinite(Date.parse(value?.ObservedAt))?new Date(value.ObservedAt).toISOString():fallbackAt;const rows=Array.isArray(value?.Items)?value.Items:(value?.Items?[value.Items]:[]);return deduplicateSensors(rows.flatMap((row,index)=>{const celsius=Number(row?.CurrentTemperature)/10-273.15;if(!validTemperature(celsius))return[];const identity=safeSensorName(row?.InstanceName,`ACPI Thermal Zone ${index}`);return[{sensor_id:`acpi:${identity.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||index}`,component:TemperatureComponent.ACPI_ZONE,sensor_name:identity,temperature_celsius:Math.round(celsius*100)/100,availability:'available',source:'windows-acpi-wmi',observed_at:observedAt,confidence:TemperatureConfidence.LOW,sensor_class:TemperatureSensorClass.ACPI_THERMAL_ZONE}];}));}
function unavailableObservation(observedAt,durationMs=0){return{schema_version:SCHEMA_VERSION,availability:'unavailable',sensors:[],providers:[],observed_at:observedAt,duration_ms:durationMs,reason:'No identity-safe temperature sensor is available.',network_requests:0,admin_required:false};}
class WindowsHardwareTemperatureCollector{
  constructor(o={}){this.platform=o.platform||process.platform;this.now=o.now||(()=>new Date());this.monotonic=o.monotonic||(()=>performance.now());this.gpuCollector=o.gpuCollector||new WindowsGpuCollector({platform:this.platform,now:this.now,monotonic:this.monotonic});const root=o.systemRoot||process.env.SystemRoot||'C:\\Windows';this.acpiProvider=o.acpiProvider||(()=>run(path.join(root,'System32','WindowsPowerShell','v1.0','powershell.exe'),['-NoLogo','-NoProfile','-NonInteractive','-Command',ACPI_SCRIPT]));}
  async collect(){const at=this.now().toISOString(),started=this.monotonic();if(this.platform!=='win32')return unavailableObservation(at,0);const [gpuResult,acpiResult]=await Promise.allSettled([this.gpuCollector.collectTemperatureSensors(),this.acpiProvider()]);const gpu=gpuResult.status==='fulfilled'?gpuResult.value:{availability:'unavailable',sensors:[]};let acpi=[];if(acpiResult.status==='fulfilled'&&!String(acpiResult.value?.stderr||'').trim())acpi=parseAcpiThermalZones(acpiResult.value.stdout,at);const sensors=deduplicateSensors([...(gpu.sensors||[]),...acpi]);const providers=[{id:'nvidia-smi',availability:gpu.availability==='available'?'available':'unavailable'},{id:'windows-acpi-wmi',availability:acpi.length?'available':'unavailable'}];if(!sensors.length)return{...unavailableObservation(at,Math.max(0,this.monotonic()-started)),providers};return{schema_version:SCHEMA_VERSION,availability:(gpu.availability==='available'&&acpi.length)?'available':'partial',sensors,providers,observed_at:at,duration_ms:Math.max(0,this.monotonic()-started),reason:null,network_requests:0,admin_required:false};}
}
class TemperatureObservationCache{
  constructor(o={}){this.now=o.now||(()=>new Date());this.ttlMs=o.ttlMs??300000;this.staleRetentionMs=o.staleRetentionMs??900000;if(!Number.isInteger(this.ttlMs)||this.ttlMs<1000||!Number.isInteger(this.staleRetentionMs)||this.staleRetentionMs<this.ttlMs)throw new RangeError('Temperature cache TTL invalid.');this.value=null;}
  set(value){this.value=JSON.parse(JSON.stringify(value));return this.get();}
  get(){const now=this.now().getTime();if(!this.value)return unavailableObservation(new Date(now).toISOString());const age=Math.max(0,now-Date.parse(this.value.observed_at));if(age>this.staleRetentionMs)return unavailableObservation(new Date(now).toISOString());const stale=age>this.ttlMs;const copy=JSON.parse(JSON.stringify(this.value));copy.cache={state:stale?'stale':'fresh',age_ms:age,ttl_ms:this.ttlMs};copy.sensors=copy.sensors.map(x=>({...x,freshness:{state:stale?'stale':'fresh',age_ms:age,stale_after_ms:this.ttlMs}}));return copy;}
  clear(){this.value=null;}
}
class TemperatureSensorService{
  constructor(o={}){this.collector=o.collector||new WindowsHardwareTemperatureCollector(o);this.cache=o.cache||new TemperatureObservationCache(o);this.onObservation=o.onObservation||null;}
  async observe(){const value=await this.collector.collect();this.cache.set(value);if(this.onObservation)await this.onObservation(this.cache.get());return this.cache.get();}
  current(){return this.cache.get();}
  slowTask(){return()=>this.observe();}
}
function selectPrimarySensor(sensors,component){const rank={high:3,medium:2,low:1};return(sensors||[]).filter(x=>x.availability==='available'&&x.component===component).sort((a,b)=>(rank[b.confidence]||0)-(rank[a.confidence]||0)||b.temperature_celsius-a.temperature_celsius||a.sensor_id.localeCompare(b.sensor_id))[0]||null;}
module.exports={ACPI_SCRIPT,TEMPERATURE_CAPABILITY_MATRIX,TemperatureComponent,TemperatureConfidence,TemperatureObservationCache,TemperatureSensorClass,TemperatureSensorService,WindowsHardwareTemperatureCollector,deduplicateSensors,normalizeSensor,parseAcpiThermalZones,selectPrimarySensor,validTemperature};
