import { assertValidHistoricalTaskUsage, assertValidProjectEstimateBrief, assertValidResourceProposal, assertValidTokenForecast, stableSha256 } from './contracts.mjs';
import { buildWorkGraphs } from './work-graph-builder.mjs';
import { calibrateGraphs } from './historical-calibrator.mjs';
import { buildAllocationProposal } from './allocation-proposal.mjs';
import { buildCopyableSummary } from './copyable-summary.mjs';

function add(map,key,value){map[key]=(map[key]??0)+value;}
function summarize(graph){
  const result={path_type:graph.path_type,graph_id:graph.graph_id,work_units:structuredClone(graph.work_units),total_input_tokens:0,total_cached_input_tokens:0,total_output_tokens:0,total_reasoning_tokens:0,total_tokens:0,calls:0,calls_by_model:{},tokens_by_model:{},tokens_by_role:{},tokens_by_phase:{},risk_drivers:[...new Set(graph.work_units.flatMap((u)=>u.risk_factors))],assumptions:[...graph.assumptions],historical_evidence_refs:[...graph.historical_evidence_refs]};
  for(const unit of graph.work_units) for(const call of unit.call_estimates){result.total_input_tokens+=call.input_tokens;result.total_cached_input_tokens+=call.cached_input_tokens;result.total_output_tokens+=call.output_tokens;result.total_reasoning_tokens+=call.reasoning_tokens??0;result.total_tokens+=call.total_tokens;result.calls++;add(result.calls_by_model,call.model_class,1);add(result.tokens_by_model,call.model_class,call.total_tokens);add(result.tokens_by_role,call.execution_role,call.total_tokens);add(result.tokens_by_phase,unit.phase,call.total_tokens);}
  return result;
}
function quality(brief){if(brief.known_task_plan?.length||brief.planned_features.length>=3&&brief.known_modules.length>=2)return'DETAILED';if(brief.planned_features.length||brief.product_scope.length)return'STRUCTURED';return'PARTIAL';}
function confidence(inputQuality,historyStatus){if(inputQuality==='DETAILED'&&historyStatus==='AVAILABLE')return'HIGH';if(inputQuality!=='PARTIAL'&&historyStatus!=='EMPTY')return'MEDIUM';return'LOW';}
function aggregateResource(path,billingMode){const calls=path.work_units.flatMap((u)=>u.call_estimates.map((c)=>({...c,task:u.work_unit_id}))).filter((c)=>c.billing_mode===billingMode);const totals={input_tokens:0,cached_input_tokens:0,output_tokens:0,reasoning_tokens:0,total_tokens:0,calls:calls.length,tokens_by_model:{}};for(const call of calls){totals.input_tokens+=call.input_tokens;totals.cached_input_tokens+=call.cached_input_tokens;totals.output_tokens+=call.output_tokens;totals.reasoning_tokens+=call.reasoning_tokens??0;totals.total_tokens+=call.total_tokens;add(totals.tokens_by_model,call.model_class,call.total_tokens);}return{...totals,task_count:new Set(calls.map((c)=>c.task)).size,context_tokens:totals.input_tokens};}

export class ProjectTokenIntelligenceEngine {
  forecast({brief:input,historyRecords=[]}){
    const brief=assertValidProjectEstimateBrief(structuredClone(input));const history=structuredClone(historyRecords);for(const record of history)assertValidHistoricalTaskUsage(record);const baseGraphs=buildWorkGraphs(brief);const calibration=calibrateGraphs(baseGraphs,history);
    const paths={optimistic_path:summarize(calibration.graphs.optimistic),expected_path:summarize(calibration.graphs.expected),conservative_path:summarize(calibration.graphs.conservative)};
    const inputQuality=quality(brief);const semantic={brief,graphs:Object.values(calibration.graphs).map((g)=>g.graph_id),history_refs:Object.values(calibration.graphs).flatMap((g)=>g.historical_evidence_refs)};
    const forecast=assertValidTokenForecast({schema_version:'0.1',record_type:'TOKEN_FORECAST',forecast_id:`forecast_${stableSha256(semantic)}`,project_summary:{project_id:brief.project_id,project_name:brief.project_name,project_goal:brief.project_goal,module_count:brief.known_modules.length,feature_count:brief.planned_features.length},forecast_version:'0.1.0',input_quality:inputQuality,forecast_confidence:confidence(inputQuality,calibration.historical_data_status),historical_data_status:calibration.historical_data_status,historical_export_required:calibration.historical_export_required,...paths,pricing_snapshot_ref:brief.pricing_snapshot_ref,entitlement_snapshot_ref:brief.entitlement_snapshot_ref,prediction_method:{core:'PROJECT_SEMANTIC_WORK_GRAPH',monte_carlo:false,probability_sampling:false,historical_average_times_task_count:false,fixed_path_ratios:false},metadata:{business_runtime_network:0,real_api_calls:0}});
    const allocation=buildAllocationProposal({forecast,expectedGraph:calibration.graphs.expected});const api=aggregateResource(paths.expected_path,'API_TOKEN_BILLED');const subscription=aggregateResource(paths.expected_path,'SUBSCRIPTION_QUOTA');
    const resources=assertValidResourceProposal({schema_version:'0.1',record_type:'RESOURCE_USAGE_PROPOSAL',resource_proposal_id:`resource_${stableSha256({forecast_id:forecast.forecast_id,api,subscription})}`,forecast_id:forecast.forecast_id,api_token_billed:{input_tokens:api.input_tokens,cached_input_tokens:api.cached_input_tokens,output_tokens:api.output_tokens,reasoning_tokens:api.reasoning_tokens,total_tokens:api.total_tokens,calls:api.calls,tokens_by_model:api.tokens_by_model},subscription_quota:{input_tokens:subscription.input_tokens,cached_input_tokens:subscription.cached_input_tokens,output_tokens:subscription.output_tokens,reasoning_tokens:subscription.reasoning_tokens,total_tokens:subscription.total_tokens,calls:subscription.calls,tokens_by_model:subscription.tokens_by_model,task_count:subscription.task_count,context_tokens:subscription.context_tokens,monetary_cost:null},pricing_snapshot_ref:brief.pricing_snapshot_ref,entitlement_snapshot_ref:brief.entitlement_snapshot_ref,pricing_authority:'03-01 AI资产成本',entitlement_authority:'03-01 AI资产成本',monetary_forecast_status:brief.pricing_snapshot_ref?'READY_FOR_EXTERNAL_CALCULATION':'PRICING_SNAPSHOT_REQUIRED',metadata:{subscription_api_price_conversion:false}});
    return{brief,graphs:calibration.graphs,forecast,allocation,resources,copyable_summary:buildCopyableSummary({brief,forecast,allocation,resources})};
  }
}
