import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { buildSessionAwareShadow, compareShadowForecast } from './session-aware-forecast.mjs';
import { buildRuleRegistry } from './structural-rule-registry.mjs';
import { buildShadowBriefFromPlan } from './shadow-plan-intake.mjs';
import { ProjectTokenIntelligenceEngine } from './forecast-engine.mjs';

const json=value=>`${JSON.stringify(value,null,2)}\n`;
export async function runGoalECommand(options,{rootDir,bounded,readJson}){
 if(!['session-forecast','shadow-calibration','calibration-compare'].includes(options.command))return null;
 if(options.command==='session-forecast'){if(!options.output||!options.evidence_class)return 2;let graphs,forecast,brief=null;if(options.plan){if(!options.project_id)return 2;brief=buildShadowBriefFromPlan(await readFile(bounded(rootDir,options.plan),'utf8'),{project_id:options.project_id});const replay=new ProjectTokenIntelligenceEngine().forecast({brief});graphs=replay.graphs;forecast=replay.forecast;}else{if(!options.graphs||!options.forecast)return 2;graphs=await readJson(bounded(rootDir,options.graphs));forecast=await readJson(bounded(rootDir,options.forecast));}const out=bounded(rootDir,options.output);await mkdir(out,{recursive:true});const shadows={};for(const [key,pathName]of[['optimistic','optimistic_path'],['expected','expected_path'],['conservative','conservative_path']])shadows[key]=buildSessionAwareShadow({graph:graphs[key],productionForecastPath:{...forecast[pathName],forecast_id:forecast.forecast_id},evidence_class:options.evidence_class});await writeFile(join(out,'session-aware-shadow.json'),json(shadows),'utf8');await writeFile(join(out,'shadow-source-graphs.json'),json(graphs),'utf8');await writeFile(join(out,'shadow-source-forecast.json'),json(forecast),'utf8');if(brief)await writeFile(join(out,'shadow-plan-brief.json'),json(brief),'utf8');process.stdout.write(`${JSON.stringify({status:'SHADOW_READY',paths:Object.fromEntries(Object.entries(shadows).map(([k,v])=>[k,v.total_tokens]))})}\n`);return 0;}
 if(options.command==='calibration-compare'){if(!options.shadow||!options.old||!options.actual||!options.case_id||!options.evidence_class||!options.output)return 2;const shadows=await readJson(bounded(rootDir,options.shadow)),old=await readJson(bounded(rootDir,options.old)),actual=Number(options.actual);if(!Number.isInteger(actual)||actual<0)return 2;const comparison=compareShadowForecast({case_id:options.case_id,actual_tokens:actual,old_forecast:old,shadows,evidence_class:options.evidence_class});const output=bounded(rootDir,options.output);await mkdir(dirname(output),{recursive:true});await writeFile(output,json(comparison),'utf8');process.stdout.write(`${JSON.stringify({status:'READY',case_id:comparison.case_id,improved:comparison.improved})}\n`);return 0;}
 if(options.command==='shadow-calibration'){if(!options.comparisons||!options.output)return 2;const files=String(options.comparisons).split(',').map(x=>x.trim()),comparisons=[];for(const file of files)comparisons.push(await readJson(bounded(rootDir,file)));const registry=buildRuleRegistry({comparisons,evidenceRefs:files});const out=bounded(rootDir,options.output);await mkdir(out,{recursive:true});await writeFile(join(out,'structural-rule-registry.json'),json(registry),'utf8');process.stdout.write(`${JSON.stringify({status:'READY',registry_id:registry.registry_id,rules:registry.rules.map(x=>x.promotion.status)})}\n`);return 0;}
}
